### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by ibrahimkoujar** [iegomez/mosquitto-go-auth#10]
Hello 
I am trying to build this package and I have zero knowledge in go.
after install golang and gogcc etc.
this error appeared 
`go build -buildmode=c-archive go-auth.go
go-auth.go:15:2: cannot find package "plugin" in any of:
	/usr/src/plugin (from $GOROOT)
	/home/ik/go/src/plugin (from $GOPATH)
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1
`

What can I do to fix this problem.

thanks..

**Comment by iegomez** [comment]
Hi! What OS are you running? This package allows to write custom backends using Go's plugin package (https://golang.org/pkg/plugin/), which only supports Linux and macOS.

If that's the problem (i.e., you are running Windows), then the direct "fix" is to modify go-auth.go and remove the custom plugin funcionality and then build the package. An alternative could be to run mosquitto and this package in a docker container with some Linux distro.

**Comment by ibrahimkoujar** [comment]
Thanks for your response the problem solved I was installed go in wrong way.

But there is another problem and that's why I moved from jpmens package to this one

the problem is when user try to connect to the broker its work normally but when he try subscribe to unauthorized topic the package disconnecting the user socket from broker, its happened only with subscribe.

Thanks.

**Comment by ibrahimkoujar** [comment]
mqtt client app

`var mqtt = require('mqtt');

var mqttClient = mqtt.connect('mqtt://localhost:1883', {
	username: "device_1",
	password: "secret",
});

mqttClient.on('connect', function () {
	mqttClient.subscribe("topic2");
	console.log("App connected to MQTT Broker!");
});`

**Comment by iegomez** [comment]
Sorry for the delay. The behavior you are seeing is from mosquitto, not a particular plugin. Mosquitto will disconnect the client when not authorized, so you must handle reconnection at the frontend.

**Comment by iegomez** [comment]
I see that indeed it was a problem at mosquitto as per this issue: https://github.com/eclipse/mosquitto/issues/1016.
I'll close this issue now as it's not related to the plugin and it was fixed there.

Thanks for bringing it up and getting them to solve it!
