### ISSUE TITLE
Clarify/Specify 'Known Bugs' in Custom Implementation

### ISSUE THREAD

**Issue by sirockin** [iegomez/mosquitto-go-auth#104]
Hi @iegomez, thanks for maintaining this repo.

I am interested in using the `Custom` implementation but am obviously worried about the 'known bugs' referred to in the readme. Do you have any further information on these - ie what they are and how to reproduce them?

Thanks!

**Comment by iegomez** [comment]
Hey, @sirockin! Go's docs for plugin used to say exactly that without specifying what those bugs were, not it only lists supported platforms and asks to report issues: https://golang.org/pkg/plugin/
I'll change the readme to reflect that.

**Comment by iegomez** [comment]
Already added the correction to the readme. Thanks again!
