### ISSUE TITLE
Files backend: Fatal error if ACL contains user not listed in password file

### ISSUE THREAD

**Issue by sirockin** [iegomez/mosquitto-go-auth#107]
When using the files backend, if the ACL contains a user not listed in the password file, the plugin returns a fatal error and mosquitto shuts down:
```
`level=fatal msg="Backend register error: couldn't initialize files backend with error read acls: Files backend error: user user_not_in_acl
does not exist for acl at line 15."
```

This is different to 'standard' ACL/password behaviour for mosquitto, which silently ignores the ommission.

I would argue that this should not be a fatal error (by all means log a warning though) for the following reasons:

1. The admin may wish to temporarily disable a user by removing their password but not want to get rid of their ACL
2. For consistency and ease of comprehension, Files backend behaviour should mimic as closely as possible the standard Mosquitto implementation

**Comment by iegomez** [comment]
Sorry about that, @sirockin , and thanks for noticing. Already fixed in 1.2.1.

Cheers!
