### ISSUE TITLE
ACL is not working at all with PostgreSQL

### ISSUE THREAD

**Issue by ShivamJoker** [iegomez/mosquitto-go-auth#110]
Hello, I have a table in my db for ACL but the rules aren't working at all
here is the ACL query and other config

```
#db config
auth_opt_pg_user thingsAdmin
auth_opt_pg_password somepass 
auth_opt_pg_dbname thingsDb
auth_opt_pg_userquery SELECT password FROM "user" WHERE email = $1 LIMIT 1 
auth_opt_pg_aclquery SELECT topic FROM acl WHERE (email = $1) 
auth_opt_log_level debug
```

The user auth seems to be working fine, but ACL isn't working at all
Here is my db
```
thingsDb=# select * from acl;
         id          |      user_id         |      topic      |       email        | rw 
---------------------+---------------------+-----------------+--------------------+----
 0fd52edf-524beddd | 7a6771-24fa311e6240 | channels/testme | hi@creativeshi.com |  2
```

Running pub sub like this
```
❯ mosquitto_pub -h localhost -p 1883 -t test -m "works fine" -u hi@creativeshi.com -P password 
```
and the message gets published

Please help thanks!

**Comment by iegomez** [comment]
@ShivamJoker The backend gets `username` and `acc` from Mosquitto for the check, and Postgres backends tries to use both in the query. Since yours doesn't mention the second one, it fails. If you don't wanna check `acc`, then just do something like `$2 = $ 2`, e.g.:
```
auth_opt_pg_aclquery SELECT topic FROM acl WHERE (email = $1) AND $2 = $2
```

**Comment by ShivamJoker** [comment]
Actually I tried same as example then I removed the ```rw = $2``` to check if it works like that or not, but I was still able to publish messages.

But now I am noticing that we are able to pub/sub but it seems messages are not reaching if I am not subscribed to topic specified is this the default behaviour ?

**Comment by ShivamJoker** [comment]
Okay I guess this was issue with mosquitto_pub/sub client cause this all seems to be working fine with MQTT.js

**Comment by iegomez** [comment]
@ShivamJoker Can this be closed then?

**Comment by ShivamJoker** [comment]
Yes sure and thanks for this amazing library
