### ISSUE TITLE
Files backend acl `read` keyword not working

### ISSUE THREAD

**Issue by sirockin** [iegomez/mosquitto-go-auth#117]
Using the latest docker image (1.2.0) and the following ACL, any subscription I attempt from that user is rejected by the backend. 

```
user cloudservice
topic read #
```

If I remove the `read` keyword, the subscription works (but obviously so do publishes!).

**Comment by iegomez** [comment]
Duplicate: https://github.com/iegomez/mosquitto-go-auth/issues/118
