### ISSUE TITLE
Files backend `read` keyword in ACL not working

### ISSUE THREAD

**Issue by sirockin** [iegomez/mosquitto-go-auth#118]
Using the latest docker image (1.2.0) and the following ACL, any subscription I attempt from that user is rejected by the backend. 

```
user cloudservice
topic read #
```

If I remove the `read` keyword, the subscription works (but obviously so do publishes!).

**Comment by iegomez** [comment]
@sirockin Could you try with a specific topic or adding a `subscribe` rule too? That should work fine.

I can't recall the specifics, but a couple of years ago, when `MOSQ_ACL_SUBSCRIBE` (4) value for `acc` was introduced, it was recommended that `subscribe` access was granted either if the specific rules was passed, or if `read` access was given for topics other than general `#` wildcard. Notice that the Files backend supports explicit `subscribe` rules as well as the scenario I described. See: https://github.com/iegomez/mosquitto-go-auth/blob/master/backends/files.go#L323

**Comment by sirockin** [comment]
Will do - and sorry for the duplicate, not sure what happened there.

**Comment by iegomez** [comment]
@sirockin Could you confirm that works so I may close this?

**Comment by robinschneider** [comment]
I am using this payload with mongodb and read does not work for me as well

**Comment by iegomez** [comment]
@robinschneider Were you able to resolve your issue? If not, could you provide more details?
