### ISSUE TITLE
Unexpected ACL access mode on PostgreSQL backend

### ISSUE THREAD

**Issue by MaxKayan** [iegomez/mosquitto-go-auth#119]
Hello! First of all, thanks for this great plugin. 👍 Trying to set it up with Django PostgreSQL right now, and having some troubles with understanding the ACL. Specifically, i am getting unexpected numbers in the second argument (access permission)

So, the project doc says:
```
... $2 is
replaced with the integer value 1 signifying a read-only access attempt
(SUB) or 2 signifying a read-write access attempt (PUB).

In the following example, the table has a column rw containing 1 for
readonly topics, 2 for writeonly topics and 3 for readwrite topics:
```

So in same explanation, `2` is described first as read-write, and then it's write-only.

Now, what i receive in PostgreSQL query log:
Upon connection & subcription i get this:
```
LOG:  execute <unnamed>: SELECT topic FROM mqtt_mqttacl WHERE username = $1 AND access_mode = $2
DETAIL:  parameters: $1 = 'testUser', $2 = '4'
```
**As you can see, the access mode integer is `4` upon subscription. What does the `4` mode mean?**

Then, when i try to send a message to the allowed topic:
```
LOG:  execute <unnamed>: SELECT topic FROM mqtt_mqttacl WHERE username = $1 AND access_mode = $2
DETAIL:  parameters: $1 = 'testUser', $2 = '2'
LOG:  execute <unnamed>: SELECT topic FROM mqtt_mqttacl WHERE username = $1 AND access_mode = $2
DETAIL:  parameters: $1 = 'testUser', $2 = '1'
```
So it always would try to check for a `2` mode, and then if it finds that entry, it checks for `1` mode. (if `2` mode not found, it just stops and returns ACL `False`) 
That leaves me having to add 3 SQL ACL entries for a user to have a read-write access in one topic. 
What is the right way to do a read-write access?

Am i doing something wrong? Can someone please clear it up for me? Thanks! 😃

**Comment by iegomez** [comment]
Hi, @MaxKayan, and thanks for your kind words.

> So in same explanation, 2 is described first as read-write, and then it's write-only.
Sorry, that's bad wording from some very old docs, I'll fix it.

> As you can see, the access mode integer is 4 upon subscription. What does the 4 mode mean?
If you check the Readme, you'll see the ACL access values: https://github.com/iegomez/mosquitto-go-auth#acl-access-values. Indeed `4` stands for subscription, which is sent from a client at the moment it subscribes to a topic. Notice this is not the same as `read`, with value `1`, which is sent on effectively reading a published message to a topic.

So, in summary, if you want to grant `read`, `write` and `subscribe` access, then yes, you'd need to have an ACL for each. Notice that you can easily circumvent this though, e.g. by defining that another value like `3` means all access, so then you can have your ACL query be:
```
SELECT topic FROM mqtt_mqttacl WHERE username = $1 AND (access_mode = $2 OR access_mode = 3)
```
Then, granting all access to users you want to would be as easy as setting records with `access_mode` 3, while you can keep checking for specific access for any other records:
```
-- username -- | -- topic -- | -- acc--
----------------------------------------------
 user          |  topic/1    |       3
```
Does that help?

Cheers!

**Comment by MaxKayan** [comment]
Yes, that does help, thanks a lot!
