### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by gjt211** [iegomez/mosquitto-go-auth#12]
Hi I am having trouble on a centos7 system.

I have installed the following;
```
go
libwebsockets
libwebsockets-devel
c-ares
c-ares-devel
openssl
openssl-devel
uuid
uuid-devel
gcc-c++
```
I set the go path as `export PATH=$PATH:/usr/local/go/bin` as per the go instructions. I created the test go application and compiled/ran it ok.

I then git cloned this repository, changed to the directory and ran make.

Output is as follows;
```
[gjt211@vps1 mosquitto-go-auth]$ go build -buildmode=c-archive go-auth.go
go-auth.go:17:2: cannot find package "github.com/go-redis/redis" in any of:
	/usr/local/go/src/github.com/go-redis/redis (from $GOROOT)
	/home/gjt211/go/src/github.com/go-redis/redis (from $GOPATH)
go-auth.go:18:2: cannot find package "github.com/iegomez/mosquitto-go-auth/backends" in any of:
	/usr/local/go/src/github.com/iegomez/mosquitto-go-auth/backends (from $GOROOT)
	/home/gjt211/go/src/github.com/iegomez/mosquitto-go-auth/backends (from $GOPATH)
go-auth.go:11:2: cannot find package "github.com/sirupsen/logrus" in any of:
	/usr/local/go/src/github.com/sirupsen/logrus (from $GOROOT)
	/home/gjt211/go/src/github.com/sirupsen/logrus (from $GOPATH)
```

**Comment by iegomez** [comment]
Hi! You are missing Go dependencies. This should work: `make requirements`.
Then you can build with a simple `make`.

**Comment by gjt211** [comment]
Hi @iegomez 
Thank you for your initial response, and your follow-up message.
I am currently away from home until the end of the week. I will certainly be checking over the weekend and will update/close with my results depending on the outcome.

**Comment by iegomez** [comment]
Hi, @gjt211.

Any luck testing?

**Comment by iegomez** [comment]
Hi! No problem.

Best regards.

**Comment by iegomez** [comment]
I'll close this issue for inactivity, but feel free to reopen it or a new one if you have any more trouble.

**Comment by sanhardik** [comment]
I am facing the following issue while trying to run `make`

```
go: extracting google.golang.org/genproto v0.0.0-20190502173448-54afdca5d873
go: extracting golang.org/x/text v0.3.2
go build -buildmode=c-shared -o go-auth.so
# github.com/iegomez/mosquitto-go-auth
/tmp/go-build747005042/b001/_x003.o: In function `mosquitto_auth_acl_check':
./auth-plugin.c:92: undefined reference to `mosquitto_client_id'
./auth-plugin.c:93: undefined reference to `mosquitto_client_username'
collect2: error: ld returned 1 exit status
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2
```
