### ISSUE TITLE
auth_opt_cache_refresh not working

### ISSUE THREAD

**Issue by grafolean** [iegomez/mosquitto-go-auth#126]
Hi @iegomez!

First of all, thank you for providing this plugin, appreciate it!

Just noticed a small typo which means that option `auth_opt_cache_refresh` does not work:
```golang
    if refresh, ok := authOpts["cache_rfresh"]; ok && refresh == "true" {
```

Note the missing `e` in `"cache_rfresh"`.

Let me know if you would prefer a PR, happy to make it.

**Comment by iegomez** [comment]
Hi, @grafolean, and thanks for catching that typo! PR works for me, but if not I'll fix it later today.
