### ISSUE TITLE
Password file and ACL are not reloaded on SIGHUP when using files backend

### ISSUE THREAD

**Issue by mrdc** [iegomez/mosquitto-go-auth#131]
Hello,

Unfortunately, password file and ACL file are not reloaded on SIGHUP when using files backend. Files are reloaded only on mosquitto restart.
By default mosquitto reloads password file, acl file and mosquitto.conf on SIGHUP, so there is no need to restart mosquitto process.
Also when I remove ACL for a user in ALC file, user still has access to all topics - is it some sort of ACL caching?

**Comment by iegomez** [comment]
I'll need to check if Mosquitto passes the signal along so files may be reloaded.

For you second topic, are you using the plugin's cache? There are separate options to set expiration times for user and ACL checks.

**Comment by mrdc** [comment]
> For you second topic, are you using the plugin's cache? There are separate options to set expiration times for user and ACL checks.

My mosquitto-go-auth settings:
```
auth_opt_backends files
auth_opt_cache true
auth_opt_cache_reset true
auth_opt_auth_cache_seconds 30
auth_opt_acl_cache_seconds 30
auth_opt_log_file /var/log/mosquitto/mosquitto.log
auth_opt_password_path /etc/mosquitto/psw_go_auth
auth_opt_acl_path /etc/mosquitto/acls
```

**Comment by iegomez** [comment]
@mrdc were you able to solve your second issue?

As for the first, this PR adds files reloading on SIGHUP.

Cheers!
