### ISSUE TITLE
Documentation is wrong for option pg_sslmode require 

### ISSUE THREAD

**Issue by devpack42** [iegomez/mosquitto-go-auth#132]
The option for using sslmode require for postgres is documented wrong. The documentation says: pg_sslmode require but this doesn't work. In the source code file the option is compared against sslmode require**d**. If you set the option pg_sslmode require**d** it works.
Please adapt the documentation or fix the comparision of the sslmode.

**Comment by iegomez** [comment]
@devpack42 Thanks for catching that typo, already fixed the code comparison and pushed to master.

Cheers!
