### ISSUE TITLE
failed to build due to unknown type 'mosquitto_plugin_id_t'

### ISSUE THREAD

**Issue by DefProc** [iegomez/mosquitto-go-auth#139]
When trying to build for mosquitto 2.0.4 (both installed via apt and manual make install) on Ubuntu 20.04, I hit this error when building mosquito-go-auth.

Error is: 

```
root@ubuntu-20.04:~/mosquitto-go-auth# make
Bulding for Linux
env CGO_CFLAGS="-I/usr/local/include -fPIC" go build -buildmode=c-archive go-auth.go
env CGO_LDFLAGS="-shared " go build -buildmode=c-shared -o go-auth.so
# github.com/iegomez/mosquitto-go-auth
In file included from auth-plugin.c:7:
/usr/local/include/mosquitto_plugin.h:167:46: error: unknown type name ‘mosquitto_plugin_id_t’
  167 | mosq_plugin_EXPORT int mosquitto_plugin_init(mosquitto_plugin_id_t *identifier, void **userdata, struct mosquitto_opt *options, int option_count);
      |                                              ^~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:13: all] Error 2
```

I did get this to build by adding the an include for `mosquitto_broker.h`, which calls the header that defines `mosquitto_plugin_id_t` above the include for `mosquitto_plugin.h`, but feels like it's not the right way to do things.

auth-plugin.c, line 6:
```cpp
#include <mosquitto.h>
#include <mosquitto_broker.h>
#include <mosquitto_plugin.h>
```

 It's entirely possible that just moving the mosquitto_plugin.h import below the line 17 will solve it too.

**Comment by iegomez** [comment]
@DefProc Thanks for reporting this, I'll give it a check as soon as I get some time.

**Comment by manuelmaurer** [comment]
It looks like this happened when they upgraded the mosquitto API from v4 to v5. While v4 is still supported and all the functions are still there, the new v5 functions now use the mosquitto_plugin_id_t structure as parameters. With the current version of the auth-plugin.c file, this creates two requirements:

1) You need to include mosquitto_broker.h before mosquitto_plugin.h, as this contains the typedefs for the new plugin which are required in the plugin header
2) You need to include mosquitto_plugin.h before mosquitto_broker.h, as this contains the definition for MOSQ_AUTH_PLUGIN_VERSION

which of course is not possible.

It will compile (tested against the current master of mosquitto) if you remove the check for the plugin version and put the broker up top:
```
diff --git a/auth-plugin.c b/auth-plugin.c
index 69c5e7c..e0aebc5 100644
--- a/auth-plugin.c
+++ b/auth-plugin.c
@@ -3,14 +3,12 @@
 #include <stdio.h>
 #include <errno.h>

+#include <mosquitto_broker.h>
 #include <mosquitto.h>
 #include <mosquitto_plugin.h>



-#if MOSQ_AUTH_PLUGIN_VERSION >= 3
-# include <mosquitto_broker.h>
-#endif

 #if MOSQ_AUTH_PLUGIN_VERSION >= 3
 # define mosquitto_auth_opt mosquitto_opt
```

On my test machine this compiles against mosquitto 2.0.5 and 1.6.12 (both git versions) and on my production machine against 2.0.5 from the Ubuntu PPA. Not sure about the implications though, especially towards older versions.

**Comment by iegomez** [comment]
@manuelmaurer Awesome, thanks for investigating!

Would you mind opening a PR with the changes? I can later check that it complies against 1.4.x to be sure.

**Comment by manuelmaurer** [comment]
> Would you mind opening a PR with the changes? I can later check that it complies against 1.4.x to be sure.
Sure, no problem

**Comment by kaluginvlad** [comment]
> It looks like this happened when they upgraded the mosquitto API from v4 to v5. While v4 is still supported and all the functions are still there, the new v5 functions now use the mosquitto_plugin_id_t structure as parameters. With the current version of the auth-plugin.c file, this creates two requirements:
> 
> 1. You need to include mosquitto_broker.h before mosquitto_plugin.h, as this contains the typedefs for the new plugin which are required in the plugin header
> 2. You need to include mosquitto_plugin.h before mosquitto_broker.h, as this contains the definition for MOSQ_AUTH_PLUGIN_VERSION
> 
> which of course is not possible.
> 
> It will compile (tested against the current master of mosquitto) if you remove the check for the plugin version and put the broker up top:
> 
> ```
> diff --git a/auth-plugin.c b/auth-plugin.c
> index 69c5e7c..e0aebc5 100644
> --- a/auth-plugin.c
> +++ b/auth-plugin.c
> @@ -3,14 +3,12 @@
>  #include <stdio.h>
>  #include <errno.h>
> 
> +#include <mosquitto_broker.h>
>  #include <mosquitto.h>
>  #include <mosquitto_plugin.h>
> 
> 
> 
> -#if MOSQ_AUTH_PLUGIN_VERSION >= 3
> -# include <mosquitto_broker.h>
> -#endif
> 
>  #if MOSQ_AUTH_PLUGIN_VERSION >= 3
>  # define mosquitto_auth_opt mosquitto_opt
> ```
> 
> On my test machine this compiles against mosquitto 2.0.5 and 1.6.12 (both git versions) and on my production machine against 2.0.5 from the Ubuntu PPA. Not sure about the implications though, especially towards older versions.

Thank you very much! I've successfully compiled this plugin on Raspberry Pi3

**Comment by iegomez** [comment]
Fixed by @manuelmaurer 's PR: https://github.com/iegomez/mosquitto-go-auth/pull/141
Thanks again, Manuel!
