### ISSUE TITLE
Mosqutio not starting after setup.

### ISSUE THREAD

**Issue by thilojaeggi** [iegomez/mosquitto-go-auth#140]
Hi there.

I've just finished up setting up Mosquitto and adding the necessary lines to mosquitto.conf and making a seperate directory "conf.d" as per instructions.
![image](https://user-images.githubusercontent.com/20727326/104134464-e99df400-5389-11eb-9e99-9402f147b364.png)
![image](https://user-images.githubusercontent.com/20727326/104134472-f589b600-5389-11eb-99d6-5d74159c5932.png)
Yet, when I try to start Mosquitto it doesn't work.
![image](https://user-images.githubusercontent.com/20727326/104134485-0df9d080-538a-11eb-99ed-c36506a7741b.png)
Does anyone know what the reasoning behind this might be?

Thank you.

**Comment by iegomez** [comment]
@thilojaeggi Could you run manually and see what error it throws?

**Comment by thilojaeggi** [comment]
My bad. It throws that the mysql setup isn't done.
Thanks!
