### ISSUE TITLE
hasher argon2id: Constant value mismatched

### ISSUE THREAD

**Issue by kencho214** [iegomez/mosquitto-go-auth#143]
Hi, I am trying to use postgres as a backend. and I found typo.

https://github.com/iegomez/mosquitto-go-auth/blob/e116ab6796fe41ec67a87a49f3b65bf605f4bb4d/hashing/hashing.go#L24

And README.md tells it in lower case.

> You may set the desired general hasher with this option, passing either `pbkdf2`, `bcrypt` or `argon2id` values. When not set, the option will default to `pbkdf2`.

Which is the expected constant value, "argon2id" (doc) or "argon2ID" (code)?

**Comment by iegomez** [comment]
You're absolutely right, @kencho214 , that's a typo. Sorry for that, I just changed the constant to be "argon2id" and already pushed the fix to master.
Thanks for catching that.

Cheers!
