### ISSUE TITLE
Building the docker image on aarch64 failed

### ISSUE THREAD

**Issue by calpit** [iegomez/mosquitto-go-auth#144]
I tried building the docker image on a Nvidia Jetson Xavier NX (aarch64).
Downloading golang failed because 'go1.13.8.linux-aarch64' doesn't exist. The correct go version would be 'go1.13.8.linux-arm64.tar.gz'.

`Step 11/23 : RUN export GO_ARCH=$(uname -m | sed -es/x86_64/amd64/ -es/armv7l/armv6l/) &&     wget https://dl.google.com/go/go${GO_VERSION}.linux-${GO_ARCH}.tar.gz &&     tar -C /usr/local -xzf go${GO_VERSION}.linux-${GO_ARCH}.tar.gz &&     export PATH=$PATH:/usr/local/go/bin &&     go version &&     rm go${GO_VERSION}.linux-${GO_ARCH}.tar.gz
 ---> Running in 6e356fbf4ec4
--2021-01-23 15:38:48--  https://dl.google.com/go/go1.13.8.linux-aarch64.tar.gz
Resolving dl.google.com (dl.google.com)... 216.58.213.238, 2a00:1450:4005:80a::200e
Connecting to dl.google.com (dl.google.com)|216.58.213.238|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-01-23 15:38:48 ERROR 404: Not Found.`

**Comment by iegomez** [comment]
Thanks for your fix, @calpit, just merged it to master.

Cheers!
