### ISSUE TITLE
Load error: go-auth.so: Undefined symbol "mosquitto_client_id"

### ISSUE THREAD

**Issue by blusewang** [iegomez/mosquitto-go-auth#147]
On FreeBSD 12  mosquitto v2.0.6
```
mosquitto -c /usr/local/etc/mosquitto/mosquitto.conf
1612157858: mosquitto version 2.0.6 starting
1612157858: Config loaded from /usr/local/etc/mosquitto/mosquitto.conf.
1612157858: Loading plugin: /root/mosquitto-go-auth-1.3.3/go-auth.so
1612157858: Error: Unable to load auth plugin "/root/mosquitto-go-auth-1.3.3/go-auth.so".
1612157858: Load error: /root/mosquitto-go-auth-1.3.3/go-auth.so: Undefined symbol "mosquitto_client_id"
```
Dos mosquitto-go-auth support mosquitto v2.0.6?

**Comment by iegomez** [comment]
It should, but no idea what flags might be needed in FreeBSD to load everything correctly. If you check the `Makefile`, you'll see some specific flags are being passed that make it work in Linux for Mosquitto 1.5.x and later, and an additional one is given for Darwin (Mac OS X). If you know how to achieve the same in FreeBSD (never tried it), I'll gladly add whatever is needed.

**Comment by blusewang** [comment]
Oh! I got it!
This issue happened on FreeBSD and the problem is in mosquitto-2.0.6.
Just clone mosquitto project and checkout fixes branch,rebuild it and install, then got work fine!
