### ISSUE TITLE
postgresql backend loops upon wrong username/password combination

### ISSUE THREAD

**Issue by jhelberg** [iegomez/mosquitto-go-auth#148]
The OpenDatabase call (db.go) connects (Open(...)) and if it succeeds, tries to ping. With bad credentials, the Open() will succeed (it actually doesn nothing) and the ping will fail. But then the call doesn't return, but sleeps in an endless loop.
Correct is to return nil, err as there is something wrong with the connect-parameters.
Maybe this is different for mysql and other databases, but the GO-docs document the behaviour of Open as a non-op.

**Comment by iegomez** [comment]
The problem with checking and erroring immediately is that the Postgres service may not be available by the time Mosquitto is running, e.g. when auto starting services with `systemd` or similar. Thus, the plugin keeps pinging the DB until it's available.

It is true that this will keep it in a loop when there is a real issue with the DB service and not just a delay on starting, so a max retries option could be useful. Thanks for bringing it up, @jhelberg!

**Comment by jhelberg** [comment]
thanks for replying so swiflty!
When using the postgresql backend, the operator of mosquitto should be aware of this dependency and add it to the systemd service file for mosquitto (or any other mechanism used). A reference to this in the README.md should be sufficient. I don't think it is right to try to solve this in the go-auth plugin, especially not as there may be no way to differentiate between a server not being there or user-credentials being faulty. My proposal is to return an error in case the ping doesn't work.
The same holds for the mysql backend, add adding the dependency to the documentation and things are solved in the right place.
thanks for the good work!

**Comment by iegomez** [comment]
Thanks again, @jhelberg, you raise good points.

Maybe `systemd` wasn't the best of examples, but there definitely are scenarios where you don't have control over startup order. Besides, logs are very clear about not being able to reach the DB when diagnosing a problem, so it hasn't been an issue so far.
But let's meet halfway, shall we? https://github.com/iegomez/mosquitto-go-auth/pull/151

Let me know how that looks to you.

Cheers!

**Comment by jhelberg** [comment]
There are two cases: the Ping fails because of an absent server or it fails because of the wrong credentials. I really dont think that Mosquitto and go-auth should do something about the first case. If a system cannot determine order, a script-wrapper around mosquitto should do that. For the wrong credentials, the call should fail, as there is no way to test user-credentials after that.
I'm OK of course with your proposed additional parameter, but I think returning (nil, err) in all ping error-cases is simpler, less confusing and more future proof. I'll close this issue and see the suggestion in #115 appear some time. Thanks for the discussion.

**Comment by iegomez** [comment]
Oh, no, thank you for the discussion! And I do agree with both points, but from a practical stance I prefer to maintain backwards compatibility and avoid myself the future issues.
