### ISSUE TITLE
Feature Request: LDAP/AD

### ISSUE THREAD

**Issue by erichiller** [iegomez/mosquitto-go-auth#150]
It would be great if LDAP was a supported method. I'd hope that you could just update / translate into Go [jpmens/mosquitto-auth-plug LDAP code](https://github.com/jpmens/mosquitto-auth-plug/blob/master/be-ldap.c).

It looks like Go has a good LDAP library [go-ldap](https://godoc.org/gopkg.in/ldap.v2) that would make it relatively painless. They even have an [example for user auth](https://godoc.org/gopkg.in/ldap.v2#ex-package--UserAuthentication).

**Comment by iegomez** [comment]
Hi, @erichiller!

It's definitely an interesting addition, but not one I want to pursue in the short term since I'm trying to avoid taking on enhancement requests myself to concentrate in long open issues and PRs. But I'd be happy to review a PR if you wish to contribute a solution.

Cheers!
