### ISSUE TITLE
Is it possible to use without hash?

### ISSUE THREAD

**Issue by rostopira** [iegomez/mosquitto-go-auth#156]
I've currently test parse server configured with anonymous auth.
I don't have passwords, but do have session tokens.
I want to use those instead of password when connecting to mosquitto.
It's stored in PostgreSQL without hash.
Is there are any option to disable hashing in this plugin?
Thanks in advance.

**Comment by iegomez** [comment]
Hi, @rostopira!
Saving passwords in plain text is not supported. You could hash your session tokens and store the hashes instead, or alternatively implement your own fetching through the custom or the JS backends.

**Comment by rostopira** [comment]
Hashing tokens on every user creation would create unnecessary overhead for database.
But nevermind, I've already added no hashing variant for myself:
```go
package hashing

type noHasher struct {
}

func NewNoHashComparer() HashComparer {
	return noHasher{}
}

func (n noHasher) Hash(password string) (string, error) {
	return password, nil
}

func (n noHasher) Compare(password, passwordHash string) bool {
	return password == passwordHash
}
```
