### ISSUE TITLE
Provide pre built binaries

### ISSUE THREAD

**Issue by ShivamJoker** [iegomez/mosquitto-go-auth#162]
Hey, it will be great if we can use pre built binaries with mosquitto or we can try compiling both in one package if it won't work independently.

**Comment by iegomez** [comment]
Hi, @ShivamJoker!
I'm not sure about releasing binaries since the plugin needs to be compiled against specific versions of Mosquitto to work correctly because their plugin interface is different per version. Also, it's a bit of a burden to release binaries when compiling the project is fairly easy. I will give it a thought, but don't expect binary releases any soon.

**Comment by ShivamJoker** [comment]
At least we can do for the latest version of mosquitto and we can use GitHub actions as well to automatically compile it.

**Comment by iegomez** [comment]
That sounds like something I'd be more willing to maintain, but I haven't played with github actions yet. Want to take a shot at it and open a PR?

**Comment by ShivamJoker** [comment]
Sure, I can give it a try but I may need bit of guidance.

Will it directly work if I just compile and get the goauth.so file ?

**Comment by iegomez** [comment]
Thanks!

> Will it directly work if I just compile and get the goauth.so file ?

I'm not entirely sure what you mean by that.

**Comment by ShivamJoker** [comment]
I mean the steps you have provided in reamde for building the plugin with mosquitto.

What do I need to do after that ?

**Comment by iegomez** [comment]
I don't know if there's an automated way to release binaries based on GitHub actions builds, I'll have to look that up.

**Comment by ShivamJoker** [comment]
@iegomez I am asking is the goauth.so file we need to make this plugin work with mosquitto ?

**Comment by iegomez** [comment]
Yeah, `goauth.so` is the only thing needed, it's the shared object that Mosquitto loads.

**Comment by iegomez** [comment]
@ShivamJoker any updates on this? Let me know if I can close it otherwise.

Cheers!

**Comment by ShivamJoker** [comment]
Hey sorry I got caught up but I'll definitely try this week

**Comment by ShivamJoker** [comment]
What I am thinking is we already have an image on dockerhub and we are publishing it on every release
And  here is the action for it by @arctic-alpaca 
https://github.com/iegomez/mosquitto-go-auth/blob/master/.github/workflows/build_and_push_docker_images.yml

What we can do is run the container with the image and copy the goauth.so file and publish it to github releases.

I also don't have much experience with the workflows if @arctic-alpaca can help it would be great.

**Comment by arctic-alpaca** [comment]
I can't currently help much with this sorry.

A first step could be to document how to get the `goauth.so` file from a Docker container to help people who can't compile it themselves. 

I'm not sure whether this is relevant. Are there differences in the resulting `goauth.so` file depending on whether glibc or musl is used by the building OS? I think I remember some issues with the Docker containers with alpine.

**Comment by iegomez** [comment]
I'm closing this for now, feel free to reopen it if there are any updates.
