### ISSUE TITLE
Redis ACL Example

### ISSUE THREAD

**Issue by suculent** [iegomez/mosquitto-go-auth#164]
I am not sure how to set :sacls and :rwacls to allow subscribing "/#" by client which worked previously without plugin.

It should subscribe to two read/readwrite channels only and write to third channel only.

**Comment by iegomez** [comment]
Hey, @suculent! Could you give any more details or a dummy example of what you're trying to achieve?

**Comment by suculent** [comment]
It seems that adding sacls “/#” and explicit topics without using hash in rwacls does it.
