### ISSUE TITLE
Error starting mqtt container on raspberry pi

### ISSUE THREAD

**Issue by Kowiste** [iegomez/mosquitto-go-auth#167]
Hi, I test your system in my windows laptop and everything go well (with postgree).
Now I'm using a RPi4 for testing (JWT) and every time I run it have the same error.

`standard_init_linux.go:219: exec user process caused: exec format error`

I try to find this file in your repository, to see what is happening but cant find anything.
I'm using the yaml that is in the docker folder. 
Do I have to configure something different?
Thanks for the repository btw

**Comment by iegomez** [comment]
You should probably apply some changes as in https://github.com/iegomez/mosquitto-go-auth/pull/163 to make it work with a RPi4 (not sure, I don't have one).

**Comment by Kowiste** [comment]
Thanks yes is because the Raspberry is ARM
