### ISSUE TITLE
arm compilation failed : build constraints exclude all Go files in ...

### ISSUE THREAD

**Issue by jinjaghost** [iegomez/mosquitto-go-auth#168]
Hi,

I've got problem cross compiling to an arm version of this plugin :
-----------------------------8<-----------------------------
1) echo $CFLAGS
-I/usr/src/jinja/mosquitto/mosquitto-1.6.9/lib -I/usr/src/jinja/mosquitto/mosquitto-1.6.9/src -fPIC

2) echo $LDFLAGS
-shared

3) env GOARCH=arm64 CGO_CFLAGS="$CFLAGS" CGO_LDFLAGS="$LDFLAGS" go build -buildmode=c-shared -o go-auth.so
package github.com/iegomez/mosquitto-go-auth: **build constraints exclude all Go files in /opt/src/golang/lib/mosquitto-go-auth**

4) go version
go version go1.15.5 linux/amd64
----------------------------->8-----------------------------

It's working well with GOARCH=amd64.

Am i doing something wrong ?

Thank you very much

**Comment by iegomez** [comment]
Hi, @jinjaghost! You could take a look at https://github.com/iegomez/mosquitto-go-auth/pull/163/files for hints on building for ARM, I don't have a way to test this.

**Comment by jinjaghost** [comment]
Installing the required libc and gcc for targeted platforms and tweaking the vars fixed the issue. Here is the working build cmd :

env **CGO_ENABLED=1 CC=aarch64-linux-gnu-gcc** GOARCH=arm64 CGO_CFLAGS="$CFLAGS" CGO_LDFLAGS="$LDFLAGS" go build -buildmode=c-shared -o go-auth.so

I am just wondering where the "**build constraints exclude all Go files**" came from.

Thanks a lot
