### ISSUE TITLE
Error when running make requirements

### ISSUE THREAD

**Issue by NoelzeN** [iegomez/mosquitto-go-auth#17]
When I try to install the Plugin, I get an error when running make requirements command.

> [root@vmi150543 mosquitto-go-auth]# make requirements
dep ensure -v
/home/nrehwald/mosquitto/src/mosquitto-go-auth is not within a known GOPATH/src
make: *** [requirements] Error 1
[root@vmi150543 mosquitto-go-auth]# echo $GOPATH
/home/nrehwald/mosquitto
[root@vmi150543 mosquitto-go-auth]# pwd
/home/nrehwald/mosquitto/src/mosquitto-go-auth

To me it looks like all is fine, files are located in $GOPATH/src/mosquitto-go-auth so I don't quite understand the error message. System is CentOS 7, versions are

> golang-bin-1.11.5-1.el7.x86_64
mosquitto version 1.6.0 (Probably irrelevant at this point in time)
mosquitto-go-auth code checked out from GitHub just a few minutes ago

Thanks for any hint what I'm doing wrong

**Comment by iegomez** [comment]
Your path is wrong, it should be $GOPATH/src/github.com/iegomez/mosquitto-go-auth. Also, Go 1.11.5 supports Go modules, you may want to enable it to let modules handle dependencies.

On another note, I just pushed a change to support mosquitto 1.6 or newer, as the plugin signatures were changed. As with 1.5.X, C flags need to be exported before building (check the readme).

**Comment by NoelzeN** [comment]
Thanks a lot for the hint iegomez, indeed changing the path fixed the error I had. For reference if anyone else has this issue in the future, my sample configuration:
>[root@vmi150543 ~]# echo $GOPATH
/home/nrehwald/mosquitto

>[root@vmi150543 ~]# cd $GOPATH/src/github.com/iegomez/mosquitto-go-auth
[root@vmi150543 mosquitto-go-auth]# pwd
/home/nrehwald/mosquitto/src/github.com/iegomez/mosquitto-go-auth

After these changed, make requirements went through without issues:

> [root@vmi150543 mosquitto-go-auth]# make requirements
dep ensure -v
(1/17) Wrote github.com/jtolds/gls@v4.2.1
(2/17) Wrote gopkg.in/mgo.v2@v2
(3/17) Wrote github.com/smartystreets/assertions@1.8.3
(4/17) Wrote github.com/sirupsen/logrus@v1.1.0
(5/17) Wrote github.com/konsorten/go-windows-terminal-sequences@master
(6/17) Wrote golang.org/x/crypto@master
(7/17) Wrote golang.org/x/sys@master
(8/17) Wrote github.com/dgrijalva/jwt-go@v3.2.0
(9/17) Wrote github.com/pkg/errors@v0.8.0
(10/17) Wrote github.com/go-redis/redis@v6.14.1
(11/17) Wrote github.com/jmoiron/sqlx@master
(12/17) Wrote github.com/gopherjs/gopherjs@master
(13/17) Wrote github.com/smartystreets/goconvey@1.6.3
(14/17) Wrote github.com/lib/pq@v1.0.0
(15/17) Wrote github.com/go-sql-driver/mysql@v1.4.0
(16/17) Wrote google.golang.org/appengine@v1.2.0
(17/17) Wrote github.com/mattn/go-sqlite3@v1.9.0

However, now I got a new error running make:

> [root@vmi150543 mosquitto-go-auth]# make
go build -buildmode=c-archive go-auth.go
go build -buildmode=c-shared -o go-auth.so
# github.com/iegomez/mosquitto-go-auth
/tmp/go-build771399479/b001/_x003.o: In function `mosquitto_auth_acl_check':
./auth-plugin.c:92: undefined reference to `mosquitto_client_id'
./auth-plugin.c:93: undefined reference to `mosquitto_client_username'
collect2: error: ld returned 1 exit status
make: *** [all] Error 2

Even though my mosquitto version is 1.6.0, it seems you have to follow the instructions of "Build the plugin for mosquitto 1.5.x" Chapter in the Readme. At least after exporting the C flagst I was able to build successfully:

> [root@vmi150543 mosquitto-go-auth]# export CGO_CFLAGS="-I/usr/local/include -fPIC"
[root@vmi150543 mosquitto-go-auth]# export CGO_LDFLAGS="-shared"
[root@vmi150543 mosquitto-go-auth]# make
go build -buildmode=c-archive go-auth.go
go build -buildmode=c-shared -o go-auth.so
go build pw-gen/pw.go

Just in case this might help anyone in the future. Thanks a lot for your help, will close the issue now.
Best Regards,
Nils
