### ISSUE TITLE
Problems installing Ubuntu 18.04

### ISSUE THREAD

**Issue by paul1982** [iegomez/mosquitto-go-auth#171]
Hello everybody,
I'm trying to use the plugin, but I make some stupid mistakes it think.
I have removed the pre-installed version of mosquitto, and installed the 1.6.9 version as discrieped on the documentation page.
Mosquitto is now running fine, with Websocket enabled.

The second step is make..
I Think is that my knowledge of Linux is not good enough, so its probable a mistake I make.
I have cloned the git in my user dir. (git clone https://github.com/iegomez/mosquitto-go-auth.git  )
go to the dir mosquitto-go-auth and run the command make.

This result in a list of faults:
env CGO_CFLAGS="-I/usr/local/include -fPIC" go build -buildmode=c-archive go-auth.go
go-auth.go:12:2: cannot find package "github.com/iegomez/mosquitto-go-auth/backends" in any of:
        /usr/lib/go-1.10/src/github.com/iegomez/mosquitto-go-auth/backends (from $GOROOT)
        /root/go/src/github.com/iegomez/mosquitto-go-auth/backends (from $GOPATH)
go-auth.go:13:2: cannot find package "github.com/iegomez/mosquitto-go-auth/cache" in any of:
        /usr/lib/go-1.10/src/github.com/iegomez/mosquitto-go-auth/cache (from $GOROOT)
        /root/go/src/github.com/iegomez/mosquitto-go-auth/cache (from $GOPATH)
go-auth.go:14:2: cannot find package "github.com/iegomez/mosquitto-go-auth/hashing" in any of:
        /usr/lib/go-1.10/src/github.com/iegomez/mosquitto-go-auth/hashing (from $GOROOT)
        /root/go/src/github.com/iegomez/mosquitto-go-auth/hashing (from $GOPATH)
go-auth.go:15:2: cannot find package "github.com/sirupsen/logrus" in any of:
        /usr/lib/go-1.10/src/github.com/sirupsen/logrus (from $GOROOT)
        /root/go/src/github.com/sirupsen/logrus (from $GOPATH)
Makefile:11: recipe for target 'all' failed

I hope someone can gif me a push in the right direction.

**Comment by iegomez** [comment]
@paul1982 Where did you place `mosquitto-go-auth`? Could you try having it at `/home/your-user/go/src/github.com/iegomez/mosquitto-go-auth` and then trying from that `dir`?
The package is using Go modules for dependencies, but I haven't done anything special with submodules so it might need to be located there (sorry, I don't do much Go since almost a year and forget about these things).

**Comment by iegomez** [comment]
Hey, @paul1982, any updates on this?

**Comment by paul1982** [comment]
@iegomez  , Thank you for your help, and sorry for my delayed reaction.

I have successful compiled the module! 
The first thing i noticed that there was no Go folder in my home dir. So I created it.
After that the strange thing happens that the sub dir, where created for me..... (I think I dit something else, because I don't be leave it created it by it self.)

After the sub dir, where visible, I tried the make command again, and now with success. But it gave a error on the one of the modules.
So I removed Go complete form Ubuntu and installed the latest version. And after that it installed correct!!
Thanks for the push in the right direction!

I'm now struggling with the login password and the PBKDF2 hash. It give the  error: received null username or password for unpwd check
While sending the string: PBKDF2$sha256$901$FUKVv9HxrEZibtml$UyYdvaXLw4n+dVyqkCjCgZxo6Bbmv2MT as password from the mqqt client to Mosquitto
But I think i need to make a different issue for that if I can not find my answer with the existing issue's

But Thanks for your help! I

**Comment by iegomez** [comment]
Good to hear that it's working now. About your second problem, I agree it should be a separate issue, but for starters you're not supposed to send the whole hash from the client, just the plain password and it'll be hashed and compared against the stored hash. So, if you created your password like this:
```
./pw -p your-password
```
And then stored it in say `Files` backend passwords:
```
your-user:hash-oh-your-password
```
Then your client needs to send `your-password`, not the output of `pw` that corresponds to `hash-oh-your-password`.
