### ISSUE TITLE
One Authentication one client

### ISSUE THREAD

**Issue by Kowiste** [iegomez/mosquitto-go-auth#172]
Hi,
I was reading but cant find any information about this, is possible to make that only one client can use one user/password. So if other try to use the same  give not authorize?

**Comment by iegomez** [comment]
Hi, @Kowiste. You're right, that is not supported nor do I think it should be for a bunch of reasons, but I'm curious about your use case. Care to expand?

**Comment by Kowiste** [comment]
Yes I would like to create a user password for every client that connect to the broker, so I can be able to revoke one client if something is wrong with it (someone have access to the client hardware for example), maybe add some limitation in the number of message per client.
What problem we could have (more CPU usage)?

**Comment by iegomez** [comment]
A priori I believe it'd be better to revoke access to the user in that case: if they have access to the hardware, they could tamper with the client id, but if they don't have another set of valid credentials they won't get authenticated after you remove them from the backend you're using.

**Comment by iegomez** [comment]
Do note that when I say not supported I mean out of the box as an option to tie a user to a clientid, you do have control over the passed options in most backends, e.g. if you have a separate http/jwt service, using gRPC, JS interpreter, etc, you can implement your auth logic however you want to.

**Comment by iegomez** [comment]
Hey, @Kowiste, I'm closing this issue for inactivty, ping me if you want to discuss further.

Cheers!
