### ISSUE TITLE
 Backend register error: couldn't initialize mysql backend 

### ISSUE THREAD

**Issue by dmsherazi** [iegomez/mosquitto-go-auth#180]
When I start mosquitto with the go auth plugin I get this error . Although I have setup the dbname, user , password and user querry

Below are the fields in cornceren from the conf file

```
auth_opt_mysql_host xxxxy
auth_opt_mysql_port 123456
auth_opt_mysql_dbname DBNAME
auth_opt_mysql_user DBUSER
auth_opt_mysql_password DBPASS 
auth_opt_mysql_connect_tries 5
auth_opt_mysql_userquery SELECT password FROM users WHERE username = ?  AND is_active = 1 LIMIT 1
auth_opt_mysql_superquery SELECT IFNULL(COUNT(*), 0) FROM users WHERE username = ? AND is_active = 1 AND is_super = 1
auth_opt_mysql_aclquery SELECT topic FROM acls WHERE username = '%s' AND (rw >= %d)

```
But still I get this error

` Backend register error: couldn't initialize mysql backend with error MySql backend error: missing options:  mysql_dbname mysql_user mysql_password mysql_userquery.`

**Comment by dmsherazi** [comment]
I found that the authplugin was loaded twice in the config so removed the second line and now I get this problem 

`g database mysql error, will retry in 2s: dial tcp: lookup db-mysql-22xxxx-do-user-1xxxx-0.b.db.ondigitalocean.com : no such host
`
although if I try on command line  the below command I can access the mysql 

`mysql -u DBUSER-h db-mysql-22xxxx-do-user-1xxxx-0.b.db.ondigitalocean.com -P 123456-D DBNAME`

further more if i use the IP address for auth_opt_mysql_host it will again print the same error 

`g database mysql error, will retry in 2s: dial tcp: lookup IPADDRESS : no such host`

**Comment by iegomez** [comment]
@dmsherazi I'm sorry but that sounds like an environment configuration problem, there's not much I can do about it without more details.

**Comment by dmsherazi** [comment]
I am using digital ocean hosted db and I think thats causing the issues. Will try to solve that. @iegomez Thanks for this awesome plugin.

**Comment by dmsherazi** [comment]
Just for those who might face this issue:

There was no issue with the env or the digital ocean. The issue was that the password in the .conf file had a trailing space which was not obvious to me when I copied it . The command line wont have an issue with a space at the end or start but the conf file of the plugin / mosquitto doesnt trim it and includes the space.

Got the clue from the mysql trouble shooting guide where it says if you get an error like below , it means you provided a wrong password. 

> **Access Denied**
> Access denied errors can look different depending on the root cause.
> 
> For example, this error means that you’re using the wrong password:
> 
>` ERROR 1045 (28000): Access denied for user 'sammy'@'203.0.113.0' (using password: YES)`
>
> 
> This access denied error means the connection string didn’t contain the -p flag but a password is required:
> 
> `ERROR 1045 (28000): Access denied for user 'sammy'@'203.0.113.0'' (using password: NO)`
> 
>
> This access denied error means the user does not have privileges on the database specified in the connection string:
> 
>` ERROR 1044 (42000): Access denied for user 'sammy'@'%' to database 'defaultdb'`
