### ISSUE TITLE
Load Balancer with mosquitto-go-auth

### ISSUE THREAD

**Issue by davidstx** [iegomez/mosquitto-go-auth#186]
More of a question than an issue

I am using a Load Balancer with 2 MQTT endpoints.  Can the the mosquitto-go-auth backend database be on the load balancer?  If its possible how would I configure mosquitto-go-auth on the endpoints to see the database on the Load Balancer?

Thanks
Regards 
David Stevenson

**Comment by iegomez** [comment]
Ho, @davidstx. I'm not sure I understand the question: what are these 2 MQTT endpoints? And if the DB or anything was behind a load balancer, would the LB expose just a single entry?

**Comment by davidstx** [comment]
Hi @iegomez

Thank you for taking the time to help me, its greatly appreciated

The client would connect to the Load Balancer and this would authenticate the user before processing the message. This would mean a single authentication database, The database would not necessary have to be on the Load Balancer 
The alternative I am trying to avoid is each mqtt server having its own database which will need to be maintained
I saw this on one of your posts 
As for the plugin’s location, the plugin.so must be in the same machine as mosquitto, but Postgres needs not to, as you can set remote host and port to access it
How do I set the remote host and port to access an external MySql database on the mqtt server which has the mosquitto-go-auth plugin

![Example](https://user-images.githubusercontent.com/64308502/128432444-b4fd8d08-1a04-45cd-b660-7a56a6e78459.JPG)

Thanks
Regards 
David Stevenson

**Comment by iegomez** [comment]
Ah, gotcha! Thanks for that diagram, @davidstx, quite helpful!

If I'm understanding correctly, you'll have a single DB handling auth for both brokers, right? And you want to set the hostname and port (as well as username, password, maybe TLS settings, etc.) for said DB.

If that's the case, MySQL backend allows to do that just as Postgres one do by setting its options:
```
auth_opt_mysql_host your-common-db-host
auth_opt_mysql_port 3306
```

You'll just need to set the same options for MySQL in both servers where there's a Mosquito instance + plugin running. You can check the available options in the readme: https://github.com/iegomez/mosquitto-go-auth#mysql

**Comment by davidstx** [comment]
Hi @iegomez 

Thanks for your help apologies I did not realise it was so simple.
Is there backend in the works for Maria DB or can the mysql settings be used on Maria DB?

Regards David

**Comment by iegomez** [comment]
Good question, @davidstx.

AFAIK, MariaDB is supported by the MySQL driver package that the backend is based on: https://github.com/go-sql-driver/mysql#features
So i want to say "yeah, it' already supported out of the box", but I'll admit to never have tried it an may be unaware of any caveats. Hopefully there are none!

**Comment by davidstx** [comment]
Hi @iegomez

I am going to see if I can get Maria DB working, I will let you know how I get on.

Thanks for your help,

Regards David
