### ISSUE TITLE
Argon2id Config Error

### ISSUE THREAD

**Issue by davidstx** [iegomez/mosquitto-go-auth#187]
Hi @iegomez 

Sorry to bug you again.

I am trying to use Argon2Id with MySql, below is what I have in my config, what am I doing wrong,  

auth_opt_mysql_hasher argon2id
auth_opt_mysql_hasher_salt_size 16           # salt bytes length
auth_opt_mysql_hasher_iterations 3           # number of iterations
auth_opt_mysql_hasher_keylen 64              # key length
auth_opt_mysql_hasher_memory 4096       # amount of memory (in kibibytes) to use
auth_opt_mysql_hasher_parallelism             # degree of parallelism (i.e. number of threads)

which is producing this error 
![start error](https://user-images.githubusercontent.com/64308502/128894057-840b864b-056e-497b-8e6e-4088ece1bbd7.JPG)

Thanks
Regards David

**Comment by iegomez** [comment]
Hi, @davidstx, no worries.

That looks similar to https://github.com/iegomez/mosquitto-go-auth/issues/125.
How are you configuring the plugin, i.e. what files are being included? Could you try throwing everything in the same file inside `conf.d`, including the `auth_plugin` option that load the plugin at the top of the file?

**Comment by davidstx** [comment]
Hi @iegomez 

Apologies, I found the error, there was a 2 missing after _auth_opt_mysql_hasher_parallelism_. Unfortunately I have another problem now, the client on sparkmqbroker01 Ip address 109.228.35.83 is not trying to connect to the database server on IP 185.132.42.82 

I have set 185.132.42.82 in the default.conf file.

![Ip address Error](https://user-images.githubusercontent.com/64308502/128946650-71747d38-b090-4b8e-bd5f-e37da4607b14.JPG)

![client connection](https://user-images.githubusercontent.com/64308502/128946610-ddd7ec40-667c-49c8-b182-9b3e091f0c10.JPG)

**default.conf** 
persistence true
#persistence_location /var/lib/mosquitto/
#persistence_file mosquitto.db
log_dest syslog
log_dest stdout
log_dest topic
log_type error
log_type warning
log_type notice
log_type information
connection_messages true
log_timestamp true

socket_domain ipv4
allow_anonymous false
#password_file /etc/mosquitto/pwfile

#listener 1883 localhost

listener 8883
certfile /etc/letsencrypt/live/broker01.sparkmq.io/cert.pem
cafile /etc/letsencrypt/live/broker01.sparkmq.io/chain.pem
keyfile /etc/letsencrypt/live/broker01.sparkmq.io/privkey.pem

listener 8083
protocol websockets
certfile /etc/letsencrypt/live/broker01.sparkmq.io/cert.pem
cafile /etc/letsencrypt/live/broker01.sparkmq.io/chain.pem
keyfile /etc/letsencrypt/live/broker01.sparkmq.io/privkey.pem

auth_plugin /opt/lib/go-auth.so
auth_opt_log_dest stdout
auth_opt_log_level debug
auth_opt_backends mysql
auth_opt_mysql_host 185.132.42.82
auth_opt_mysql_port 3306
auth_opt_mysql_dbname mosquittoauth
auth_opt_mysql_user mosquittoauth
auth_opt_mysql_password 99f99b8cd760eab40e1f04476b312999b466a2f10c9e04b358e1085cfa7422387a182771841f3c54309154078cb6fd34f659f076a8a838db8f28c0c7a7250403
auth_opt_mysql_allow_native_passwords true
auth_opt_mysql_userquery SELECT pw FROM users WHERE username = ?
auth_opt_mysql_aclquery SELECT topic FROM acls WHERE username = ? AND (rw & ?) != 0

auth_opt_mysql_hasher argon2id
auth_opt_mysql_hasher_salt_size 16 # salt bytes length
auth_opt_mysql_hasher_iterations 3 # number of iterations
auth_opt_mysql_hasher_keylen 64 # key length
auth_opt_mysql_hasher_memory 4096 # amount of memory (in kibibytes) to use
auth_opt_mysql_hasher_parallelism 2 # degree of parallelism (i.e. number of threads)

Thanks
Regards David

**Comment by iegomez** [comment]
I'm glad you worked out the other issue, @davidstx. 

For the current one, the error is saying that `'mosquittoauth'@'109.228.35.83'` does not have access to your DB instance. I don't know how you configured remote access in your DB server, maybe it's just allowing the hostname but not the IP? Can't really help much because it sounds like MySQL configuration needs troubleshooting. You could maybe write a dummy Go program that tries to connect with the credentials from your Mosquitto server and tweak your MySQL configuration until you find the issue.

On another note, prefer to paste output in text (maybe formatted as code, i.e surrounded by 3 backticks, for readability) instead of pictures, it's way easier to read and copy anything when needed. To aid readability too, try to format your conf as code as well.
And remember to redact your secrets (i.e., your mysql password in this case)! :smile:

**Comment by davidstx** [comment]
Hi @iegomez

I will have look to see if I can find anything, the client is not even getting to the database server because it trying to connect with the incorrect IP address from the authentication plugin - its as if the plugin is not seeing the ip address and using the default localhost.

The database has been set to allow remote usewrs in - I have tested this by connecting with a sql query tool from within windows.

Regards David

**Comment by davidstx** [comment]
Hi @iegomez

Completely removed every trace of MySql and MariaDB from the client, rebooted. Installed the database client and I still get the plugin trying to connect to the localhost  

Regards David

**Comment by iegomez** [comment]
@davidstx from your issue I don't see it trying to connect to the wrong host, i.e. `109.228.35.83`, it's trying to connect **from** that host, thus `'mosquitto'@'109.228.35.83'`, because that is the origin of the client. The DB is clearly responding with `denied`, hence why I mention it looks like a MySQL configuration issue that maybe isn't allowing client IPs, only hostnames.

You can test by granting access to `'mosquitto'@'109.228.35.83'` to the target DB in your DB server.

**Comment by iegomez** [comment]
You can see details in the docs: https://dev.mysql.com/doc/refman/8.0/en/connection-access.html

**Comment by davidstx** [comment]
@iegomez 

Thanks for your last reply, it helped solve the issue. Have not used MySql much and was setting it up the way I would Oracle.

In the start up info I see Extended authentication not enabled 

Is this something I need to worry about

`1628651480: Loading plugin: /etc/mosquitto/conf.d/go-auth.so
1628651480:  ├── Username/password checking enabled.
1628651480:  ├── TLS-PSK checking enabled.
1628651480:  └── Extended authentication not enabled.`

Thanks
Regards David

**Comment by iegomez** [comment]
I don't think so, that comes from Mosquitto and I'm not entirely sure what it refers to.
I'll give it a check though.

**Comment by iegomez** [comment]
@davidstx I just checked and there's nothing to worry about, this comes from Mosquitto's own security extension: https://mosquitto.org/documentation/dynamic-security/

It's printed in these bits on `security.c`:
```
	if(plugin->auth_start_v4){
		if(plugin->auth_continue_v4){
			log__printf(NULL, MOSQ_LOG_INFO,
					" └── Extended authentication enabled.");
		}else{
			log__printf(NULL, MOSQ_LOG_ERR,
					"Error: Plugin has missing mosquitto_auth_continue() function.");
			LIB_CLOSE(lib);
			return MOSQ_ERR_UNKNOWN;
		}
	}else{
		log__printf(NULL, MOSQ_LOG_INFO,
				" └── Extended authentication not enabled.");
	}
```
So feel free to dismiss that message.

**Comment by davidstx** [comment]
Hi @iegomez

Thanks for checking and thanks for all the help. 

Regards David
