### ISSUE TITLE
Startup error prebuilt docker image ARMv6

### ISSUE THREAD

**Issue by dgoebel97** [iegomez/mosquitto-go-auth#188]
Hi @iegomez,

I'm currently trying to run this software with Docker on a Raspberry Pi B+ (`ARM32v6` architecture) with the prebuilt images with this minimal `mosquitto.conf`.
```
log_dest stdout
log_timestamp false
log_type all

auth_plugin /mosquitto/go-auth.so
auth_opt_backends files
```

When I point  `auth_plugin` parameter to the correct location `/mosquitto/go-auth.so` in the docker container then the startup fails with this error.
```
mosquitto version 2.0.9 starting
Config loaded from /etc/mosquitto/mosquitto.conf.
Loading plugin: /mosquitto/go-auth.so
Error: Unable to load auth plugin "/mosquitto/go-auth.so".
Load error: /mosquitto/go-auth.so: cannot open shared object file: No such file or directory
```
I already checked that the compiled plugin is really there in the container.
```
# ls -l /mosquitto    
total 35828
drwxr-xr-x 2 root root     4096 Jul 31 04:15 auth
drwxr-xr-x 2 root root     4096 Jul 31 04:15 conf.d
-rw-r--r-- 1 root root 34108867 Jul 31 04:27 go-auth.so
-rwxr-xr-x 1 root root  2566432 Jul 31 04:27 pw
```

Moreover, when I start a container with the same config file and version on my Ubuntu 20.04 Laptop, it runs smoothly without any error.
```
mosquitto version 2.0.9 starting
Config loaded from /etc/mosquitto/mosquitto.conf.
Loading plugin: /mosquitto/go-auth.so
 ├── Username/password checking enabled.
 ├── TLS-PSK checking enabled.
 └── Extended authentication not enabled.

```

This error affects all the versions of the prebuilt images.

**Comment by iegomez** [comment]
Hi, @dgoebel97, thanks for reporting it.

Sadly, I don't use Docker (or the plugin, for that matter) nor do I have a RPi to test it on, so best I can tell you is to build from source in the RPi instead of using Docker and see what errors may come up.

Sorry for the very unhelpful response. 😅

**Comment by dgoebel97** [comment]
Hi @iegomez,

That's what I thought after reading the other docker related issues but I wanted to report this issue at least. :sweat_smile:

But compiling on the RPi leads to another issue.
I used the following versions for compiling
 * go 1.16.7
 * gcc 8.3.0
 * mosquitto 2.0.9
 * mosquitto-go-auth 1.7.0

This is the output of the build process.
```
Bulding for Linux
env CGO_CFLAGS="-I/usr/local/include -fPIC" go build -buildmode=c-archive go-auth.go
env CGO_LDFLAGS="-shared" go build -buildmode=c-shared -o go-auth.so
# github.com/iegomez/mosquitto-go-auth
/usr/bin/ld: $WORK/b001/_x003.o: in function `mosquitto_auth_unpwd_check':
./auth-plugin.c:86: undefined reference to `mosquitto_client_id'
/usr/bin/ld: $WORK/b001/_x003.o: in function `mosquitto_auth_acl_check':
./auth-plugin.c:128: undefined reference to `mosquitto_client_id'
/usr/bin/ld: ./auth-plugin.c:129: undefined reference to `mosquitto_client_username'
collect2: error: ld returned 1 exit status
make: *** [Makefile:13: all] Error 2
```
Could this be related to the compiling issues for the RPi mentioned in the README?

**Comment by dgoebel97** [comment]
That's what I thought after reading the other docker related issues but I wanted to report this issue at least :sweat_smile:

Unfortunately, I ran in a bunch of other issues when compiling it on the RPi. 
I will try it on the RPi 4 next week again and hope that then there will be no issues with the Docker images.

**Comment by dgoebel97** [comment]
On the RPi 4 it works without any problem.

Thanks for the awesome plugin. :+1:
