### ISSUE TITLE
Disconnect the client when subscribe is not authorized

### ISSUE THREAD

**Issue by sanhardik** [iegomez/mosquitto-go-auth#19]
Hello, 
Amazing work on the plugin.
I am trying to test the setup with mosquitto and the plugin. 
When I try to subscribe to a topic that a particular user is not authorized, I get a SUBACK. Should the client not get disconnected since the subscription is not authorized ?

Details:
Mosquitto version 1.5.7

I have set it up password and acls for 2 users. 

```
user admin
topic readwrite #

user test
topic subscribe test/#

user test1
topic read test/#
```

User test and test1 are only allowed to subscribe and read from topic test/#. 

However when I subscribe user test to a seperate topic, I get a SUBACK

```
mosquitto_sub -u test -P test -d  -p 1883 -t admin 
Client mosqsub|81657 sending CONNECT
Client mosqsub|81657 received CONNACK (0)
Client mosqsub|81657 sending SUBSCRIBE (Mid: 1, Topic: admin, QoS: 0)
Client mosqsub|81657 received SUBACK
Subscribed (mid: 1): 128
```

In the system log, I do see that "Acl is false for user test" 

I would like to disconnect the client for unauthorized topic if possible. 

On a seperate note, is it possible to move the log files out of system logs into a seperate log file ?

Thanks a lot.

**Comment by iegomez** [comment]
Hi!

It's up to mosquitto to decide what happens to the client connection when access is denied for some topic, there's nothing the plugin can do about it. And no, the intended behavior is not to disconnect clients (it was actually a bug a few versions ago), just not to deliver messages on that topic to unauthorized ones.

Right now logs from the plugin are directed to stderr, but it seems like a good idea to allow other options such as file. I'll get back to you when I've added the feature.

**Comment by iegomez** [comment]
I just added stderr, stdout and file log options.

**Comment by sanhardik** [comment]
@iegomez Thanks for the quick reply.
