### ISSUE TITLE
JWT in local mode with mysql

### ISSUE THREAD

**Issue by TacoNaco47** [iegomez/mosquitto-go-auth#190]
Hey there! 

First of all, thank you for all the effort you put into this mosquitto plugin. :)

Currently, I am trying to implement this into my own MQTT server, but I struggle with the JWT authentication just a bit.

This is my configuration: 

```
listener 8883

certfile /etc/mosquitto/certs/server.pem
keyfile /etc/mosquitto/certs/server.key

auth_plugin /etc/mosquitto/conf.d/go-auth.so

auth_opt_hasher pbkdf2
auth_opt_backends jwt

auth_opt_jwt_mode local
auth_opt_jwt_db mysql
auth_opt_jwt_userfield Username
auth_opt_jwt_userquery select count(*) from "test_user" where username = ? limit 1
auth_opt_jwt_secret {REMOVED FOR OBVIOUS REASON}

auth_opt_jwt_mysql_port 41081
auth_opt_jwt_mysql_sslmode skip-verify
auth_opt_jwt_mysql_sslrootcert /etc/mosquitto/certs/db_ca.pem
auth_opt_jwt_mysql_mysql_sslcert /etc/mosquitto/certs/db_client-cert.pem
auth_opt_jwt_mysql_sslkey /etc/mosquitto/certs/db_client-key.pem
auth_opt_jwt_mysql_user {REMOVED FOR OBVIOUS REASON}
auth_opt_jwt_mysql_password {REMOVED FOR OBVIOUS REASON}
auth_opt_jwt_mysql_dbname {REMOVED FOR OBVIOUS REASON}

auth_opt_cache true
auth_opt_cache_reset true
auth_opt_cache_refresh true

auth_opt_auth_cache_seconds 30
auth_opt_acl_cache_seconds 30
auth_opt_auth_jitter_seconds 3
auth_opt_acl_jitter_seconds 3

auth_opt_log_level debug
auth_opt_log_dest file
auth_opt_log_file /var/log/mosquitto/mosquitto_backend.log

```

So far, everything seems to be working (the service doesn't crash and the plugin writes accordingly into the specified file "mosquitto_backen.log"). 

However, when I try to connect with MQTT explorer I get the following error:
```
time="2021-08-30T11:41:45+02:00" level=debug msg="checking auth cache for test"
time="2021-08-30T11:41:45+02:00" level=debug msg="to auth record: [97 117 116 104 45 116 101 115 116 45 102 108 117 102 102 121 45 116 105 109 101 218 57 163 238 94 107 75 13 50 85 191 239 149 96 24 144 175 216 7 9]\n"
time="2021-08-30T11:41:45+02:00" level=debug msg="checking user test with backend JWT"
time="2021-08-30T11:41:45+02:00" level=debug msg="jwt parse error: token contains an invalid number of segments"
time="2021-08-30T11:41:45+02:00" level=info msg="jwt local get user error: token contains an invalid number of segments"
time="2021-08-30T11:41:45+02:00" level=error msg="token contains an invalid number of segments"
```

Where is the problem? 
I am frankly new to the "JWT" topic and I guess the MQTT explorer software doesn't support this kind of authentication, am I right? (or I need to authenticate in another way)

My final goal is to implement it into my broker service, which uses the [mqtt package](https://www.npmjs.com/package/mqtt) from npm.

**Comment by TacoNaco47** [comment]
Couldn't let go of this so I researched a bit more... ^^

In jpmens archived plugin repo under [JWT](https://github.com/jpmens/mosquitto-auth-plug#jwt-auth) he describes it more clear in my opinion:

> The username field is interpreted as the token-field and passed to the http-server in an Authorization-header.
> ```Authorization: Bearer %token```
> Note: Some clients require the password field to be populated. This field is ignored by the JWT-backend, so feel free to input some gibberish.

That hint "the username field is interpreted as the token-field" was crucial for me to get things right. I've just found out you stated this already:
> To clarify this, here's an example for connecting from a javascript frontend using the Paho MQTT js client (notice how the jwt token is set in userName and password has any string as it will not get checked):

But to be honest, the documentation is a bit hard to read and I would really like to help you improve it for me and others. =)

**Comment by iegomez** [comment]
Hey, @TacoNaco47!

I'm glad you found your issue, and I'm always open to review PRs to improve the docs, so feel free to open one one with more details.

Cheers!

**Comment by iegomez** [comment]
I'll close the issue for now. Feel free to reach me or open a PR with enhancements to the docs.

Cheers!
