### ISSUE TITLE
Prefix does not work with JWT plugin

### ISSUE THREAD

**Issue by paul1982** [iegomez/mosquitto-go-auth#191]
I want to use the prefix option to route the IOT devices to the mysql plugin, and the webusers to the JWT plugin.
Therefore I have to add the prefix before the JWT string.
I can see in the debug that the prefix is recognized and the JWT plugin is selected.

But the JWT token is not valid, because the prefix is added tot the string, but is not removed before it is checked.

I hope you can help me.

Thank you in advanced

**Comment by iegomez** [comment]
Hi, @paul1982!

That's really odd, since `username` is trimmed [here](https://github.com/iegomez/mosquitto-go-auth/blob/master/backends/backends.go#L361) for auth check, and [here](https://github.com/iegomez/mosquitto-go-auth/blob/master/backends/backends.go#L420) for ACL check. I'll give it a check, but do you have evidence it's checking it with the prefix included? You could throw a couple of prints in the JWT backend to see what it's checking.

**Comment by paul1982** [comment]
If I add the prefix to the token, I get this:

DEBU[2021-09-03T22:39:30+02:00] Found prefix for user WEB_eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJmaXJzdE5hbWUiOiJQYXVsIiwiaW5zZXJ0TmFtZSI6IiIsInN1ck5hbWUiOiJQb3N0IiwicGhvbmVfbnVtYmVyIjoiMDY0NTY5MDY5NSIsIm1vYmlsZV9udW1iZXIiOiIwNjQ1NjkwNjk1IiwiZW1haWwiOiJwLnBvc3RAYWtvYmUubmwiLCJyb2xlX2lkIjoyLCJyZWxhdGlvbl9pZCI6MX0sImlhdCI6MTYzMDcwMTYyMiwiZXhwIjoxNjMwNzA1MjIyfQ.8GDEilcFT-yrMUmbaL3YYx_AIL-ReyqrjTN6Z2TRtfI, using backend jwt. 

DEBU[2021-09-03T22:39:30+02:00] jwt parse error: Token used before issued    
INFO[2021-09-03T22:39:30+02:00] jwt local get user error: Token used before issued 
DEBU[2021-09-03T22:39:30+02:00] Found prefix for user WEB_eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJmaXJzdE5hbWUiOiJQYXVsIiwiaW5zZXJ0TmFtZSI6IiIsInN1ck5hbWUiOiJQb3N0IiwicGhvbmVfbnVtYmVyIjoiMDY0NTY5MDY5NSIsIm1vYmlsZV9udW1iZXIiOiIwNjQ1NjkwNjk1IiwiZW1haWwiOiJwLnBvc3RAYWtvYmUubmwiLCJyb2xlX2lkIjoyLCJyZWxhdGlvbl9pZCI6MX0sImlhdCI6MTYzMDcwMTYyMiwiZXhwIjoxNjMwNzA1MjIyfQ.8GDEilcFT-yrMUmbaL3YYx_AIL-ReyqrjTN6Z2TRtfI, using backend jwt. 
DEBU[2021-09-03T22:39:30+02:00] jwt parse error: Token used before issued    
INFO[2021-09-03T22:39:30+02:00] jwt local get user error: Token used before issued 
DEBU[2021-09-03T22:39:30+02:00] Found prefix for user WEB_eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJmaXJzdE5hbWUiOiJQYXVsIiwiaW5zZXJ0TmFtZSI6IiIsInN1ck5hbWUiOiJQb3N0IiwicGhvbmVfbnVtYmVyIjoiMDY0NTY5MDY5NSIsIm1vYmlsZV9udW1iZXIiOiIwNjQ1NjkwNjk1IiwiZW1haWwiOiJwLnBvc3RAYWtvYmUubmwiLCJyb2xlX2lkIjoyLCJyZWxhdGlvbl9pZCI6MX0sImlhdCI6MTYzMDcwMTYyMiwiZXhwIjoxNjMwNzA1MjIyfQ.8GDEilcFT-yrMUmbaL3YYx_AIL-ReyqrjTN6Z2TRtfI, using backend jwt. 

DEBU[2021-09-03T22:39:30+02:00] jwt parse error: Token used before issued    
INFO[2021-09-03T22:39:30+02:00] jwt local get user error: Token used before issued 
ERRO[2021-09-03T22:39:30+02:00] Token used before issued   

If I don't add the prefix, it works, but it will use the mysql and the jwt.

I hope this helps you.

**Comment by paul1982** [comment]
Ohhhhh I forgot,.. Thank you for your Quick response and effort

**Comment by iegomez** [comment]
@paul1982 As you can see in the logs, the JWT token gets parsed (so the prefix must have been trimmed, otherwise you'd see a different error) but there's a timing issue, thus the `Token used before issued`. I'm guessing you have a time difference between the server for the service providing the token and the server where Mosquitto is running.

**Comment by iegomez** [comment]
Notice that the token is being logged before doing the stripping, not after it's passed to the JWT backend, just in case you were wondering why you see the prefix in the logs.

**Comment by iegomez** [comment]
@paul1982 were you able to confirm that the error is related to timing issues and not the prefix?

**Comment by paul1982** [comment]
Yes iets was my fault!  It works great. The real problem was time
differents between my development systeem and the server. Sorry for my late
reaction

Op wo 15 sep. 2021 20:19 schreef Ignacio Gómez ***@***.***>:

**Comment by iegomez** [comment]
No problem, thanks for letting me know!
