### ISSUE TITLE
Mosquitto should start also without a GRPC connection

### ISSUE THREAD

**Issue by Vorlif** [iegomez/mosquitto-go-auth#192]
Currently, Mosquitto cannot be started if the plugin cannot establish the GRPC connection. GRPC however, (can) uses a reconnect mechanism and establishes a connection independently. I realize that the plugin cannot be used if GRPC is configured and the remote site is unreachable. Withal, I don't think it should keep the entire service from launching just because the connection can't be established.

We had a problem that during a system start, Mosquitto was stopped again because the GRPC connection could not be established. But the GRPC service was active a few minutes later.

I am not sure if it is in line with the philosophy of the project, but I think it would be a useful change. Maybe as an additional option?

**Comment by iegomez** [comment]
Hi, @Vorlif. Thanks for bringing this up, I think you're right and it makes sense to allow retries when attempting to create the client. I'll add it as an option.

**Comment by iegomez** [comment]
I'll admit I haven't touched the gRPC backend in a couple of years now, so if you wanna contribute a PR adding the option instead, I'll happily review it.

**Comment by Vorlif** [comment]
Hi @iegomez. Thank you for your quick reply. I would be happy to contribute something to the project. But it will take until the weekend before I can open a PR.

**Comment by iegomez** [comment]
@Vorlif I had some time and came up with an initial attempt that allows to skip dial failure on initialization and only set the client on a user or all check one the service is up. I don't really have a gRPC service running to properly give it a try, but I added some basic automated tests to check it.

Could you take the branch for a spin to see if it works for you?

**Comment by Vorlif** [comment]
@iegomez I have tested it and it works. :+1:  I left you also a suggestion as a comment in the PR.

Thanks for your effort and the project.
