### ISSUE TITLE
Complex queries for mysql

### ISSUE THREAD

**Issue by YerayAlonso** [iegomez/mosquitto-go-auth#203]
I find problems doing a complex query for the `auth_opt_mysql_userquery`.  
I found [this comment](https://github.com/jpmens/mosquitto-auth-plug/issues/31#issuecomment-58024678) which seems to suggest you can call `SET` to store the `?` variables and then use these variables in your `SELECT` call. Both calls at the same `auth_opt_mysql_userquery` line.  
However, I get an error saying the `SELECT` statement is malformed.

Is there a way to use the `?` variable multiple times in the `SELECT` call?

**Comment by iegomez** [comment]
Hi, @YerayAlonso!
I don't think there's a clean way to do it generically, you'd need access to the actual query building to set named parameters, but the idea proposed in the comment you linked seemed a reasonable enough workaround. May I ask what's your actual query and how is it failing?

**Comment by YerayAlonso** [comment]
Sorry for not explaining the situation clearly enough.  
I have two tables, `users` and `connectors`. Both them have `UserName` and `PasswordHash`, and `connectors` also has a `UseOwnerCredentials`. Then I want to search the credentials in one table or the other depending on `UseOwnerCredentials`.

I think I could get the correct `PasswordHash` without needing to use `?` multiple times with this:

```sql
auth_opt_mysql_userquery 
SELECT cons.pass FROM
  (
  SELECT connectors.UserName as username, connectors.PasswordHash as pass
  FROM connectors
  WHERE NOT connectors.UseOwnerCredentials
  UNION
  SELECT users.UserName, users.PasswordHash
  FROM connectors
  INNER JOIN users ON users.Id = connectors.OwnerId
  WHERE connectors.UseOwnerCredentials
  ) as cons
WHERE username=?
limit 1;
```

I've indented it a bit for readability, but I have it in one single line in the config file and it seems to work fine.

Thanks for replying.

**Comment by iegomez** [comment]
Cool, I'm glad you were able to figure it out!
