### ISSUE TITLE
MongoDB problem

### ISSUE THREAD

**Issue by Stayer** [iegomez/mosquitto-go-auth#21]
```
mqtt_1           | 1559595124: New connection from 172.22.0.1 on port 1883.
mqtt_1           | time="2019-06-03T20:51:58Z" level=debug msg="checking user test with backend Mongo"
mqtt_1           | time="2019-06-03T20:51:58Z" level=debug msg="Mongo get user error: command find requires authentication"
mqtt_1           | 1559595245: Socket error on client <unknown>, disconnecting.
```

My mongo configuration:
1. `admin` user with password `pass`
2. full access to any database
3. I generate password `test` for table `users` using `pw -p test`, user the same (test)
4. connection info are the same in mongo and mosquitto config

Without plugin everything works

**Comment by iegomez** [comment]
I just pushed a change because the `username` option for Mongo wasn't being set. Could you check to see if that fixes your problem by pulling the latest version?

I'll be changing the Mongo driver as `mgo` has been unmaintained for a long while. So if your problem remains unfixed with that small change, I should have the new driver running tomorrow or at least some day this week.

**Comment by Stayer** [comment]
Unfortunately, it doesn't work. The same errors

**Comment by Stayer** [comment]
The same situation with Redis backend? Can't run it

```
mqtt_1   | time="2019-06-04T03:24:12Z" level=fatal msg="\nbackends error\n"
```
I tried different redis versions, with and w/o password, different db id

**Comment by iegomez** [comment]
Could you give the Redis versions you tried? I ran the tests at work and had no issue with Redis, but maybe my version was too old and I won't be able to check until the morning (it's 00:47 here).

I'll try to finish the Mongo migration and test Redis versions during the day to see if I can get it fixed as soon as possible.

**Comment by Stayer** [comment]
Latest redis on docker (version 5.0.5) https://hub.docker.com/_/redis/
Now it's working on version 4

**Comment by iegomez** [comment]
Okay, I've just pushed some changes that include the migration to the official mongodb driver. I tried it with and without auth, all tests are passing.

I also tried and ran tests with and without auth against Redis 5.0.5 and everything worked fine. The error `backends error` doesn't have to do with the Redis connection: it's shown when the plugin's conf file provides and invalid backend, e.g., mistyping redis or some other backend.

Could you pull from master and check that both Mongo and Redis work for you? If so, I'll make a release after your confirmation.

**Comment by Stayer** [comment]
Ok, I will check very soon, thanks!

**Comment by Stayer** [comment]
Everything works! Thank you so much
