### ISSUE TITLE
Unable to run docker images 

### ISSUE THREAD

**Issue by inteldon** [iegomez/mosquitto-go-auth#211]
Thanks for your work on this docker container. 

I tried running `docker run -it --name my_mosquitto -p 1883:1883 iegomez/mosquitto-go-auth` and got an error `Error: Unable to open config file /etc/mosquitto/mosquitto.conf.` the same thing occurs with simpler docker commands to run the image. 

Please advise on what needs to be done. 

Thank you

**Comment by iegomez** [comment]
From the error I believe you're not mounting a volume with the configuration files for mosquitto and the plugin.

**Comment by inteldon** [comment]
Thanks, I tried the example shared in the code. First, I created a `/conf` directory similar to the `conf_example` folder, with structure and content. 

Then I ran the command: `docker run -it -p 1884:1884 -p 1883:1883 -v /conf:/etc/mosquitto iegomez/mosquitto-go-auth` and even after mounting the volume I got this error: `Error: Unable to open config file /etc/mosquitto/mosquitto.conf.` 

I think it's referring to the /etc/mosquitto/... structure within the container, is that correct? what other files do I need to create? 

Thanks again

**Comment by iegomez** [comment]
If you're mounting `/conf` (note that's an absolute path, did you mean that?)  into `/etc/mosquitto`, then you'll need to at least have `/conf/mosquitto.conf` for Mosquitto's configuration, and `/conf/conf.d/go-auth.conf` (or whatever you called it in you `mosquitto.conf` when including the dir) for the plugin's one.

But yeah, it boils down to Mosquitto not finding the file within the container.

**Comment by inteldon** [comment]
Thanks. Yes, I actually mounted the full path like this: 
docker run -it -p 1884:1884 -p 1883:1883 -v /home/myusername/conf:/etc/mosquitto iegomez/mosquitto-go-auth

`
1637132840: mosquitto version 2.0.12 starting
1637132840: Config loaded from /etc/mosquitto/mosquitto.conf.
1637132840: Starting in local only mode. Connections will only be possible from clients running on this machine.
1637132840: Create a configuration file which defines a listener to allow remote access.
1637132840: For more details see https://mosquitto.org/documentation/authentication-methods/
1637132840: Opening ipv4 listen socket on port 1883.
1637132840: Opening ipv6 listen socket on port 1883.
1637132840: Error: Cannot assign requested address
1637132840: mosquitto version 2.0.12 running
` 

Seems like it's working, but I'm only seeing port 1883 assigned, and not 1884. Does this look right? 

If I want to test the go-auth, is there an API reference I could use to start testing it? 

Thanks

**Comment by iegomez** [comment]
Seems like you're missing listeners in your configuration, or it's not actually loading anything and resorting to defaults: `Create a configuration file which defines a listener to allow remote access.`.
