### ISSUE TITLE
Any password can connect if use mysql auth???

### ISSUE THREAD

**Issue by hezll** [iegomez/mosquitto-go-auth#212]
We user this plugin for a long time. But recently the security team report that any password can connect the queue if the user is existed.

So we have a look and test with the source code.

It looks like the issue comes with the hash.compare function

https://github.com/iegomez/mosquitto-go-auth/blob/master/backends/mysql.go

if o.hasher.Compare(password, pwHash.String) {
                log.Debugf(" compare code true")
                return true, nil
}

Not sure why, but it looks like any string can return true with this compare funciont.
For example

o.hasher.Compare("abc", pwHash.String)  //return ture
o.hasher.Compare("asdfasfadsf", pwHash.String)  //return ture

Did some one have the same issue?

**Comment by hezll** [comment]
![image](https://user-images.githubusercontent.com/1241715/141669348-407813a7-4f0b-4710-9cc0-d9555aa051da.png)
![image](https://user-images.githubusercontent.com/1241715/141669401-adc191a2-18e9-47fc-b368-a56835f6b93f.png)
As the test code here, I just try with some simple compare,  all return true.

Thats why we can use any password to access the MQTT.
Please let me know is there any issue.

**Comment by hezll** [comment]
if o.hasher.Compare("abasdfasdfc",pwHash.String) {
                        log.Debugf("testuser__abasdfac== hashString")
                }

this "abas..." is not password at all.. In put any string , can return true here.

**Comment by hezll** [comment]
![image](https://user-images.githubusercontent.com/1241715/141736732-fe54d97e-81ff-454f-a774-54df4f4877e0.png)
solve the issue. It could be a legacy password pw utility.
It return PBKDF2$sha512$100000$lgPFxtJ3XZjNbXMBsa6q2A==$
so the splitHash[4]  return ''  then the  keylenth is 0

![image](https://user-images.githubusercontent.com/1241715/141737125-55067125-900c-4a38-9321-b73202c8284e.png)

better add:

if len(keylen) == 0 {
		log.Errorf("invalid PBKDF2 hash supplied, expected password part is missing, got: %d", len(hashSplit))
		return false
}


Btw 

you must use 

./pw - p password

can not user 
./pw  password
This will return wrong password as well if you not use -p.

**Comment by hezll** [comment]
Feel free to close this ticket. 
Thanks.

**Comment by iegomez** [comment]
I'm glad you found your problem and I'll take a look into the hashing package to see if a len check makes sense.
