### ISSUE TITLE
How to access the go auth API 

### ISSUE THREAD

**Issue by inteldon** [iegomez/mosquitto-go-auth#214]
Once the system is running, how can we access the APIs? What port is the endpoint? Are there any documentations for accessing/editing APIs? 

Thanks

**Comment by iegomez** [comment]
I'm not sure what you mean by API here, or what endpoint and port would those be. Could you share more details?

**Comment by inteldon** [comment]
In order to access the plugin to add/remove users and acls, how can I connect to the running broker to pass those variables? I was hoping that there would be some form of HTTP API to connect with MQTT in order to manage users and acls, instead of the text password file we would have database systems. 

On the other hand I'm wondering if go-auth only provides a database connection, which we need to manually manipulate, e.g. user and tables?

**Comment by iegomez** [comment]
Have you gone through the README of the project? All the options and how they are configured are listed there.

You need to preconfigure the plugin to use whatever backends you want: a DB, static files, HTTP services, etc.
You don't add or remove users and acls through the broker or the plugin, you do that in whatever backend(s) you're using.
