### ISSUE TITLE
ACL query not working for mysql

### ISSUE THREAD

**Issue by BrentLeemans** [iegomez/mosquitto-go-auth#216]
I have to following configuration:
```
auth_opt_mysql_userquery select password from mqtt_topic where username = ? and deleted_at is null limit 1
auth_opt_mysql_aclquery select topic from mqtt_topic where (username = ?) and permission = ?
```
with the following table:
```
mqtt_topic
(
    id            int auto_increment primary key,
    topic         varchar(255)  not null,
    deleted_at    datetime      null,
    username      varchar(255)  not null,
    password      varchar(255)  not null,
    permission    tinyint(1)    null
)
```
I have a user in my database with permission set to 3.
Everything works until I add the auth_opt_mysql_aclquery option. Whenever I try to subscribe, mosquitto will close my connection.

I followed the readme but couldn't figure out what's wrong, any suggestions?

**Comment by iegomez** [comment]
On subscribing clients will send `4` as the access value, `3` is for when they try to actually read a message from the topic. So you need to either add records with `4` for your topics, or rework your query to accept both.

**Comment by BrentLeemans** [comment]
I created a new table for ACL checks. Added permissions 2, 3 and 4. I now can subscribe but I can't publish anything. Do you know why? 

Also, how would I write my query so it won't check the permissions? For some topics I just want the user to publish and subscribe.

**Comment by iegomez** [comment]
Sorry, I mistyped the value, `1` is for read. As the readme shows:

```
#define MOSQ_ACL_NONE 0x00
#define MOSQ_ACL_READ 0x01
#define MOSQ_ACL_WRITE 0x02
#define MOSQ_ACL_SUBSCRIBE 0x04
```

Sorry, can't help with your query because it's absolutely app dependent, there's no generic solution.

**Comment by BrentLeemans** [comment]
I added 1, 2 and 4 as permissions and now I'm able to subscribe and publish to my topic. Thank you!

**Comment by akashtalole** [comment]
I am also facing acl issue. auth is working but acl policy not working.
`auth_opt_aclquery SELECT topic FROM test_acl WHERE (username = ?) AND rw = ?`

Observation is user can publish/subscribe to any topic but as per acl topic it is not working.

**Comment by akashtalole** [comment]
This is acl table
`+----+--------------+----------+------------+----+
| id | test_user_id | username | topic      | rw |
+----+--------------+----------+------------+----+
|  9 |           79 | nodered  | test/flow  |  2 |
+----+--------------+----------+------------+----+
`

**Comment by iegomez** [comment]
Again, the option is not correct, it should be `auth_opt_mysql_aclquery`, you're missing the `mysql` part.

**Comment by akashtalole** [comment]
Sorry my bad. Thanks for quick reply.

**Comment by malakaisbest** [comment]
> Sorry, I mistyped the value, `1` is for read. As the readme shows in https://github.com/iegomez/mosquitto-go-auth#acl-access-values:
> 
> ```
> #define MOSQ_ACL_NONE 0x00
> #define MOSQ_ACL_READ 0x01
> #define MOSQ_ACL_WRITE 0x02
> #define MOSQ_ACL_SUBSCRIBE 0x04
> ```
> 
> Sorry, can't help with your query because it's absolutely app dependent, there's no generic solution.

I'm facing the same ACL issue with the MySQL backend.
after digging into the problem I found the following thing.

when client-side use TCP 
- Read Acc value is 1
- write  Acc value is 2

when client-side use MQTT over Websocket
 - Write  Acc value is 2 (Same as TCP)
 - But the reading Acc value is 4.

finally, I think we haven't a solution for this yet

**Comment by iegomez** [comment]
@malakaisbest  Are you sure about that? 4 should be to initially subscribe to a topic, not to read from it later. So there's a bug in the client, it's misconfigured or being misused, but there's nothing to tweak in the broker or plugin configuration wise for that.

Of course, you can always work around it to allow both values for readers by reshaping or modifying your data, your query, or both. But that's absolutely specific to your app, so there's nothing I can suggest a priori without knowing more details about it.

**Comment by iegomez** [comment]
Oh, if you do provide more details, could you open a separate issue or reopen this one?

**Comment by malakaisbest** [comment]
Sorry for the delayed reply.
after searching, I found this issue from the client side.
every JS example that I found and chrome extensions like [MQTT BOX](https://chrome.google.com/webstore/detail/mqttbox/kaajoficamnjijhkeomgfljpicifbkaf) send ACC value 4 when subscribing to the topic and receiving messages.

i already tried  [PHP mqtt](https://github.com/php-mqtt/client) client and MQTT BOX tcp feature.
those applications send ACC value 1 when subscribing to the topic and receiving messages.


then I found [HiveMQ](http://www.hivemq.com/demos/websocket-client/) online WSS client. this online client works like the TCP application...

I will update this when I succeed.
thank you for your support @iegomez

**Comment by malakaisbest** [comment]
example [mqttws31.js](https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.js) code on [eclipse.org](https://www.eclipse.org/paho/index.php?page=clients/js/index.php) is giving that ACC 4 issue.

then I used [mqttws31.js](http://www.hivemq.com/demos/websocket-client/js/mqttws31.js) on hivemq.com.
it resolves the issue.

thanks

**Comment by iegomez** [comment]
I'm glad to read you resolved your issue.

As for the clients always sending either 1 or 4 for both subscribe/read, but not the correct one for each action, I think that's wrong and not compliant with Mosquitto's interface. They probably get away with it when there's no strict check on those, but it seems terribly buggy to me.

But anyway, that's their problem, not yours, and again, I'm glad you were able to fix it.

Cheers!
