### ISSUE TITLE
Switch to a semver compliant docker image tag syntax

### ISSUE THREAD

**Issue by ralftar** [iegomez/mosquitto-go-auth#219]
The current docker registry tag syntax is not getting picked up by dependabot when newer versions are released.

Switching to a [senver](https://semver.org/) compliant tag syntax would allow automated tools to pick up new versions.

Dependabot trace where `1.8.1-mosquitto_1.6.14` is **not** the latest version:

```
updater | INFO <job_237003448> Checking if iegomez/mosquitto-go-auth 1.8.1-mosquitto_1.6.14 needs updating
updater | INFO <job_237003448> Latest version is 1.8.1-mosquitto_1.6.14
```

**Comment by iegomez** [comment]
Could you file a PR for this?

**Comment by iegomez** [comment]
I'll try to work on this next week, is just the order in which the tag is built: plugin version first and Mosquitto version last.
If we swap them, then it should work.

**Comment by iegomez** [comment]
@ralftar  I haven't had the time to do so, care to file a PR with that change?

**Comment by iegomez** [comment]
There was no PR, thus I'll close this.
