### ISSUE TITLE
Unknown configuration variable mysql_host when using prebuilt docker image

### ISSUE THREAD

**Issue by akashtalole** [iegomez/mosquitto-go-auth#220]
mosquitto.conf
`persistence true
persistence_location /var/lib/mosquitto/
log_type all
listener 1883
listener 1884
protocol websockets
allow_anonymous false
include_dir /mosquitto/conf.d
`
goauthmysql.conf

`auth_plugin /mosquitto/go-auth.so
auth_opt_backends mysql
auth_opt_mysql_protocol tcp
mysql_host db
mysql_port 3306
mysql_user go_auth_test
mysql_password go_auth_test
mysql_dbname go_auth_test
mysql_userquery select password_hash from "user" where username = $1 limit 1
mysql_superquery select count(*) from "user" where username = $1 and is_admin = true
mysql_aclquery select distinct 'application/' || a.id || '/#' from "user" u inner join organization_user ou on ou.user_id = u.id inner join organization o on o.id = ou.organization_id inner join application a on a.organization_id = o.id where u.username = $1 and $2 = $2
`

Getting below error while running container
`1638180773: Loading config file /mosquitto/conf.d/mos.conf
1638180773: Error: Unknown configuration variable "mysql_host".
1638180773: Error found at /mosquitto/conf.d/mos.conf:5.
1638180773: Error found at /etc/mosquitto/mosquitto.conf:17.
`

**Comment by iegomez** [comment]
Sorry for the delay, bur from what you pasted you are missing the `auth_opt_` for the `mysql_host` option.
Could you confirm and later close the issue if so, @akashtalole?

**Comment by akashtalole** [comment]
@iegomez Thanks it is working now.
