### ISSUE TITLE
Connection refused: not authorized when trying to subscribe

### ISSUE THREAD

**Issue by vijaygh1996** [iegomez/mosquitto-go-auth#222]
Hi
I am trying to implement MQTT authentication using MySQL as backend, The auth plugin running under docker container, which I have created a DB and tables and I have set it up password and acls for few users. hashed user credentials using pbkdf2 but when I am trying to access or authorize a user the below things are happening.

mosquitto version 2.0.14
MySQL 5.7
 

mosquitto_sub -h <Host_ip> -p 1883 -d -t test  -u user -P userpass

Client (null) sending CONNECT
Client (null) received CONNACK (5)
Connection error: Connection Refused: not authorised.
Client (null) sending DISCONNECT

mosquitto-go-auth container logs:
error: received null username or password for unpwd check
1638939980: Sending CONNACK to auto-38BB8794-3FA8-0784-A2AA-C6F30FF63393 (0, 5)
1638939980: Client auto-38BB8794-3FA8-0784-A2AA-C6F30FF63393 disconnected, not authorised.

What will be the solution , root cause? or traceback
Thanks in advance

**Comment by iegomez** [comment]
This is thrown here, before it ever gets to be checked by any backend: https://github.com/iegomez/mosquitto-go-auth/blob/master/auth-plugin.c#L91

The [2.0.14 release](https://mosquitto.org/blog/2021/11/version-2-0-14-released/) doesn't show any changes to the function signature, so I honestly have no idea why the username or password would be null.
