### ISSUE TITLE
Auth only called once

### ISSUE THREAD

**Issue by zainali-mrs** [iegomez/mosquitto-go-auth#226]
Hi,

I am using this plugin (v1.5.0) with "auth_opt_backends" http. I have setup "auth_opt_http_getuser_uri" with endpoint "/mqttAuth" which gets called when new user tries to connect to MQTT broker. I noticed that if somehow call to this endpoint "/mqttAuth" fails once then it does not gets called again. E.g. if on first try, I provide wrong password for connection to broker, "/mqttAuth" gets called and password does not match and i return 401. Then i again try to connect with correct password then this endpoint is not called again. To make it work again, i have to restart docker containers. Also after restart, it work once only.
Is there any configuration i have to do in conf file to cater for this problem?

```
auth_plugin /mosquitto/go-auth.so
auth_opt_backends http
auth_opt_http_host myLocalHost
auth_opt_http_port 3000
auth_opt_http_with_tls false
auth_opt_http_getuser_uri /mqttAuth
auth_opt_http_superuser_uri /mqttSuperUser
auth_opt_http_aclcheck_uri /mqttAcl

auth_opt_cache true
auth_opt_cache_type go-cache
auth_opt_cache_reset true
auth_opt_cache_refresh true

auth_opt_auth_cache_seconds 60
auth_opt_acl_cache_seconds 300
auth_opt_auth_jitter_seconds 5
auth_opt_acl_jitter_seconds 30

auth_opt_retry_count 3
```

Thanks

**Comment by zainali-mrs** [comment]
@iegomez 
Yes, but tried after that as well. Tried to connect after 1 minute and still the "mqttAuth" endpoint was not getting called.

**Comment by iegomez** [comment]
Could you set the log level to `debug` and check what's being called? There could be a bug in the Go cache code.
Also, is there a reason to be using such an outdated version?

**Comment by zainali-mrs** [comment]
Sure, i will set log level to debug.
No specific reason for older version, this version was latest when we started using it. Did not got a proper change to integrate authentication mechanism until now.

**Comment by zainali-mrs** [comment]
Ok, I understand the problem.
I had problem with my setup. I had one script running which was trying to continuously reconnect. Also i was doing it manually with MQTT.fx.  I closed the script and tried to reconnect with MQTT.fx after 1 minute and it worked. The auth endpoint got called then. So the cache time gets reset once someone tries to connect and my background script was reconnecting again and again never letting 1 minute mark pass.

So the problem was with my test setup and my failure to understand the cache time mechanism. I have to set them properly now. 
@iegomez  Thanks for the hints, and sorry to bother you.

**Comment by iegomez** [comment]
No problem, @zainali-mrs, I'm glad you figured it out.

Cheers!
