### ISSUE TITLE
Restart needed for change in ACL

### ISSUE THREAD

**Issue by sanhardik** [iegomez/mosquitto-go-auth#23]
Hello, 
This is more of a question then an issue. 

I am using the files backend
While adding new users and acls, does mosquitto need to be restarted on every new addition or change ?

I tried changing acl's but they didnt get picked up until I restarted mosquitto

**Comment by iegomez** [comment]
Yes, static acls are loaded on startup. If you need to dynamically add or remove users and acls I suggest using a different backend for that.

**Comment by sanhardik** [comment]
Thanks @iegomez
