### ISSUE TITLE
Support pbkdf2 with PHC format?

### ISSUE THREAD

**Issue by IoTThinks** [iegomez/mosquitto-go-auth#245]
Hi all,
Does the library support pbkdf2 with PHC format?
Some of my programs start to use pbkdf2 with PHC format.
https://github.com/P-H-C/phc-string-format/blob/master/phc-sf-spec.md#specification

pbkdf2 with PHC format: 
$pbkdf2-sha512$i=10000,l=32$WOmVx2TXXXXXX85Hk/LtiA$lE1AXXXXXXd4tqX3Ebg0wu9cJhbQF6gcd0FIWzVcA5k

Current PBKDF2 format
PBKDF2$sha512$10000$oWJmWbLOQuiXXXXXXKk58Q$tdXCk6r4V6Htxzd7CgBx/DrmCxcXfcOAudhQ1XXXXXX

Thanks a lot and have a nice day.

**Comment by IoTThinks** [comment]
Added some hints to convert into PHC format.

https://meta.discourse.org/t/export-password-hashes-in-the-phc-format/133805

**Comment by iegomez** [comment]
It does not at the time, but I would welcome a contribution to support it.
Alternatively, I could implement it myself, but I can't give an ETA for it other than "not soon".

**Comment by iegomez** [comment]
I'm closing this issue since no one has contributed with the requested support and, as mentioned, my ETA for such feature remains to be "not soon".

Feel free to open another issue if you want to contribute with such implementation.

Cheers!
