### ISSUE TITLE
Dynamic topics names

### ISSUE THREAD

**Issue by Enhed** [iegomez/mosquitto-go-auth#249]
Hello, i have topic with example structure:  
`system/devices/{{id}}/messages`

where id is id of device, but i have more than 20k devices and many users with different access to them, so generating acl for that is hurt. Its possible to create dynamic subscribe? for example:  
`system/devices/+/messages` - for all devices with user have access  
`system/devices/1,2,3,4/messages` - access only in `[1,2,3,4]` ids with check access on them  
or maybe exists another way to make it easily?
p.s. i use pg db

**Comment by Enhed** [comment]
@iegomez the request is now there and it functions, but only in the case of a 1 to 1 subscription. But how to allow using `+` receiving messages only from available devices is not clear

**Comment by iegomez** [comment]
Take a look at https://www.chirpstack.io/project/guides/mqtt-authentication/ as an example. In the plugin configuration section there's an `acl` query that builds topics on the fly derived from the user data, allowing wildcard access to anything under `application` topics given the user's organization:
```
auth_opt_pg_aclquery select distinct 'application/' || a.id || '/#' from "user" u inner join organization_user ou on ou.user_id = u.id inner join organization o on o.id = ou.organization_id inner join application a on a.organization_id = o.id where u.email = $1 and $2 = $2
```

So the point is that depending on where the allowed `ids` for your devices messages come from, you need to represent that in the form of a query to return topics to match against. The plugin can't "support" having `system/devices/1,2,3,4/messages` for you, that's not how the DB backends work.
