### ISSUE TITLE
Clarification for HTTP backend

### ISSUE THREAD

**Issue by jmollerhoj** [iegomez/mosquitto-go-auth#264]
The option http_post under HTTP backend is marked as mandatory. In the comments field it is stated: IP address,will skip dns lookup

Does that mean, that only an IP address not a host name will be valid or does it mean that if an IP address is entered no DNS lookup will be made as opposed to if a host name is entered?

**Comment by iegomez** [comment]
That part is so old that I honestly can't remember why it says that, but just omit it: you can pass a hostname or an IP, and it will work.
