### ISSUE TITLE
git-ignore Gopkg.lock?

### ISSUE THREAD

**Issue by henryk** [iegomez/mosquitto-go-auth#27]
`dep ensure` (as executed by `make requirements`) autogenerates/updates `Gopkg.lock`.
This leads to an unclean checkout for basically every user of `make requirements`.
Maybe `Gopkg.lock` should be removed from the repository and added to `.gitignore`?

**Comment by iegomez** [comment]
I haven't used `dep` in quite a while and was actually thinking about removing it and just keep Go modules. But I see at least you are using it, so I've just removed the lock file. This means that reproducible builds are left to the user.
