### ISSUE TITLE
cloudflare jwt token "key is of invalid type"

### ISSUE THREAD

**Issue by deddy2101** [iegomez/mosquitto-go-auth#270]
hi i'm using token given from cloudflare zero trust. when i submit the token (created by cloudflare) in the debug console i get 
time="2023-04-12T15:56:22Z" level=debug msg="jwt parse error: key is of invalid type"
time="2023-04-12T15:56:22Z" level=info msg="jwt get claims error: key is of invalid type"
time="2023-04-12T15:56:22Z" level=error msg="key is of invalid type"

my config of mosquitto is the following:

#ports / protocols
listener 1883
protocol mqtt

listener 9001
protocol websockets

allow_anonymous false

#persistance 
persistence true
persistence_location /var/lib/mosquitto

log_dest file /var/log/mosquitto/mosquitto.log

include_dir /etc/mosquitto/conf.d

# auth_go
auth_plugin /mosquitto/go-auth.so
auth_opt_log_level debug
auth_opt_backends jwt

auth_opt_jwt_mode js
auth_opt_jwt_secret                                                                 
auth_opt_jwt_parse_token true
auth_opt_jwt_js_user_script_path /etc/mosquitto/jwt/parsed_user_script.js
auth_opt_jwt_js_superuser_script_path /etc/mosquitto/jwt/superuser_script.js
auth_opt_jwt_js_acl_script_path /etc/mosquitto/jwt/acl_script.js

hope u can help me

**Comment by iegomez** [comment]
I can't since I don't know what your token looks like or how it was signed.
I'd suggest searching for something like `go jwt key is of invalid type`, that shows a bunch of results that may be related to your issue.

**Comment by deddy2101** [comment]
thanks for the fast response, here is how cloudflare suggest to check if the token is valid [https://developers.cloudflare.com/cloudflare-one/identity/authorization-cookie/validating-json/](url)
i got a Application Audience (AUD) Tag that i tried as auth_opt_jwt_secret but it doesn't seems to be the correct key. i'll try searching on the internet and let u know
thanks

**Comment by iegomez** [comment]
That AUD wouldn't work, that's not the signing key which needs to be set as the `uth_opt_jwt_secret` option.

**Comment by deddy2101** [comment]
from the infromation that i understood my signature encryption algorithm is rs256 so i don't have a private key to use for validation. i have a public key to do so. can i do it with js setting `auth_opt_jwt_parse_token false` and providing the code in `auth_opt_jwt_js_user_script_path`.
am i right?

**Comment by deddy2101** [comment]
i solved the problem by adding a new type of jwt backend, and cecking the publik key in golang using jwt.parse
code is the following 

`package backends

import (
	"crypto/rsa"
	"crypto/x509"
	"encoding/pem"
	"fmt"
	"github.com/dgrijalva/jwt-go"
	log "github.com/sirupsen/logrus"
	"os"
)

type goJWTChecker struct {
	pubCertRsa     *rsa.PublicKey
	pubCertRsaPath string
	options        tokenOptions
}

func NewGoBckChecker(authOpts map[string]string, options tokenOptions) (jwtChecker, error) {
	checker := &goJWTChecker{
		options: options,
	}
	if pubCertPath, ok := authOpts["jwt_go_pubcert_path"]; ok { //if ok is not empty then...
		log.Debugf("Path given to go-auth: ->" + pubCertPath)
		data, err := os.ReadFile(pubCertPath)
		if err != nil {
			fmt.Println("Errore nella lettura del file:", err)
			return nil, err
		}
		pubCertConverted, err := StringToRSAPublicKey(data)
		if err != nil {
			log.Debugf("error in certificate conversion")
			return nil, err
		} else {
			checker.pubCertRsa = pubCertConverted
		}
	} else {
		log.Debugf("empty publick Key path")
		return nil, nil
	}

	return checker, nil
}

func (o *goJWTChecker) GetSuperuser(username string) (bool, error) {
	return false, nil
}

func (o *goJWTChecker) CheckAcl(username, topic, clientid string, acc int32) (bool, error) {
	return true, nil
}

func (o *goJWTChecker) GetUser(token string) (bool, error) {
	//params := map[string]interface{}{
	//	"token": token,
	//}
	success, err := VerifyJWTSignature(token, o.pubCertRsa)
	if err != nil {
		log.Debugf("go error : #{err}")
	}
	return success, err
}

func (o *goJWTChecker) Halt() {
	// NO-OP
}

// Funzione per verificare la firma di un token JWT
func VerifyJWTSignature(tokenStr string, publicKey *rsa.PublicKey) (bool, error) {
	// Parsa il token JWT
	token, err := jwt.Parse(tokenStr, func(token *jwt.Token) (interface{}, error) {
		// Verifica il metodo di firma
		if _, ok := token.Method.(*jwt.SigningMethodRSA); !ok {
			return nil, fmt.Errorf("metodo di firma non supportato: %v", token.Header["alg"])
		}
		return publicKey, nil
	})

	if err != nil {
		return false, fmt.Errorf("errore durante il parsing del token JWT: %v", err)
	}

	// Verifica se il token JWT è valido
	if token.Valid {
		fmt.Println("Token Valid")
		return true, nil
	} else {
		fmt.Println("Token inValid")
		return false, nil
	}
}

// Funzione per convertire una stringa in un valore di tipo *rsa.PublicKey
func StringToRSAPublicKey(publicKeyStr []byte) (*rsa.PublicKey, error) {
	// Parsa la chiave pubblica PEM
	block, _ := pem.Decode(publicKeyStr)
	if block == nil {
		fmt.Println("Errore durante la decodifica PEM della chiave pubblica")
	}
	// Parse della chiave pubblica
	cert, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		fmt.Println("Errore durante il parsing della chiave pubblica:", err)
	}
	rsaPublicKey := cert.PublicKey.(*rsa.PublicKey)
	fmt.Println("Rsa Pub Key N", rsaPublicKey.N)
	fmt.Println("Rsa Pub Key E", rsaPublicKey.E)

	return rsaPublicKey, nil
}
`

**Comment by iegomez** [comment]
@deddy2101 bravo!
I'm glad you were able to make it work for your case. I'm on a mini vacation right now and haven't looked at the code, so I'll just ask: is this something that's too specific to your use case, or do you see this as a valid generic solution for Cloudflare and maybe other services based tokens? I'm asking in case there's value in merging such a JWT option into the general plugin.

Cheers!
