### ISSUE TITLE
Wrong error codes in acl check

### ISSUE THREAD

**Issue by sudobhat** [iegomez/mosquitto-go-auth#28]
(auth-plugin.c line 99 and 111)
When the acl check returns 500, the error code is  MOSQ_ERR_ACL_DENIED. But it should be  MOSQ_ERR_UNKNOWN.

In the C plugin, the error codes are correct.

**Comment by iegomez** [comment]
I believe you mean when an HTTP or JWT backend returns 500, not the acl check.
Mosquitto only has these returns for acl checks:
```
*	MOSQ_ERR_SUCCESS if access was granted.
 *	MOSQ_ERR_ACL_DENIED if access was not granted.
 *	MOSQ_ERR_UNKNOWN for an application specific error.
 *	MOSQ_ERR_PLUGIN_DEFER if your plugin does not wish to handle this check.
```
So when you say:

> When the acl check returns 500, the error code is MOSQ_ERR_ACL_DENIED. But it should be MOSQ_ERR_UNKNOWN.

I agree it's useful to tell a 200 (or another) code with an error from a 500 code, but the available returns don't map to https status codes and thus the specific return is an implementation detail.

> In the C plugin, the error codes are correct.

You mean in https://github.com/jpmens/mosquitto-auth-plug? Again, that plugin decided that any 5xx status code corresponded to an `MOSQ_ERR_UNKNOWN`, but `mosquitto` doesn't impose anything here, it doesn't even care that it's an HTTP backend the one responding. For example, that plugin doesn't handle redirects or client (3xx and 4xx) errors and just `defers` the response:

```
	re = curl_easy_perform(curl);
	if (re == CURLE_OK) {
		re = curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &respCode);
		if (re == CURLE_OK && respCode >= 200 && respCode < 300) {
			ok = BACKEND_ALLOW;
		} else if (re == CURLE_OK && respCode >= 500) {
			ok = BACKEND_ERROR;
		} else {
			//_log(LOG_NOTICE, "http auth fail re=%d respCode=%d", re, respCode);
		}
	} else {
		_log(LOG_DEBUG, "http req fail url=%s re=%s", url, curl_easy_strerror(re));
		ok = BACKEND_ERROR;
	}
```

Now, maybe that's a good way to handle http requests and I'm open to start a discussion in this same issue about what the plugin should do in each case. But then I'd also like to include other backends in said discussion so the semantics of `MOSQ_ERR_UNKNOWN` are clear, well documented and understandable **in the scope of this plugin in specific**.

What do you think?

**Comment by sudobhat** [comment]
Hello, Thanks for the reply.

>  but mosquitto doesn't impose anything here, it doesn't even care that it's an HTTP backend the one responding. 

It is true, but with the error code MOSQ_ERR_ACL_DENIED, mosquitto does not disconnect from the client. But, when the error code is  MOSQ_ERR_UNKNOWN, mosquitto is disconnected from the client.

At least for me, it is useful to have the possibility to disconnect mosquitto from the client in the event of ACL check failure. (in case of http backend)

**Comment by iegomez** [comment]
What version of mosquitto are you using? I'm not sure that disconnection is the desired result and it was indeed a [bug](https://github.com/iegomez/mosquitto-go-auth/issues/10) on an earlier version of mosquitto.

**Comment by iegomez** [comment]
Do you know where I can find documentation for this? I just want to make sure any decision is justified.

In any case, as I said, this would not be a light change. For starters, a faulty http service could disconnect clients which don't even expect to be authed against an external http service and would be correctly allowed access weren't for the faulty backend. Thus this needs discussions and clear rules, so I'd really appreciate your insights on what you think should be expected from the plugin in different scenarios, not only a 5xx from http/jwt backends, but also other kind of failures in other backends.

**Comment by iegomez** [comment]
Since there was no feedback for the proposed discussion, I'll close this.
