### ISSUE TITLE
JWT remote mode acl route issue

### ISSUE THREAD

**Issue by alessandroperetti** [iegomez/mosquitto-go-auth#284]
Hi,

I am using JWT remote mode with `user`, `superuser` and `acl` route checks.
Right now I am using only the `acl` route for checking the permissions. The permission is provided by a remote service so it takes sometimes (depending on the network traffic or parallel requests).
The problem is that if the `acl` route not responds before 5 seconds I got  `read ECONNRESET` from mqtt client. otherwise everything works as expected.
I tried it mocking the remote permission services with a timeout and I can confirm that if the timeout is less then 5000 ms everything is ok otherwise I got the error above.
Likely, I think it is a timeout problem but I can't find any general configuration options to enlarge it or a workaround to solve it.

Opening the container where Mosquitto resides I see:

`context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

Thanks
AP

**Comment by alessandroperetti** [comment]
I opened the PR for adding a custom parameter: `https://github.com/iegomez/mosquitto-go-auth/pull/285`

**Comment by iegomez** [comment]
Thanks for opening a PR. There are a few issues and I need to check why tests are not running on external PRs, probably some misconfigured setting on my side.

**Comment by alessandroperetti** [comment]
I ll fix them. Tks

**Comment by alessandroperetti** [comment]
let me know the test file where you expect the test.

**Comment by alessandroperetti** [comment]
Sry for the issues but I am not very skilled in go. 
Now should be better.

**Comment by iegomez** [comment]
Addressed by https://github.com/iegomez/mosquitto-go-auth/pull/285.
