### ISSUE TITLE
Error in run tests with docker and mounted volume

### ISSUE THREAD

**Issue by alessandroperetti** [iegomez/mosquitto-go-auth#286]
Hi all, 

I spent a lot of time in trying to run tests with a mounted volume in Docker ( avoiding the need to rebuild image according to the documentation) because I got `error obtaining VCS status: exit status 128` during the  `docker run`.

I solved it with adding ` -buildvcs=false` in plugin `Makefile` :

```go build -buildvcs=false -buildmode=plugin```

Do you have the same problem @iegomez ?

AP

**Comment by alessandroperetti** [comment]
Great! I did not notice it

**Comment by iegomez** [comment]
It's a Go thing that was introduced some time ago si I'm not very keen to include it as part of the plugin's docs.
But at least now we have this issue for people to reference if they face a similar situation.

I'll close this now as it's not really an issue in the plugin.
