### ISSUE TITLE
Compilling on arm.

### ISSUE THREAD

**Issue by jboulton** [iegomez/mosquitto-go-auth#29]
Hi,
I'm having problems compiling on an Odroid C2 running ubuntu 18.04. I'm getting 
$go build -buildmode=c-shared -o go-auth.so
# github.com/iegomez/mosquitto-go-auth
/tmp/go-build779123523/b001/_x003.o: In function `mosquitto_auth_acl_check':
auth-plugin.c:(.text+0x430): undefined reference to `mosquitto_client_id'
auth-plugin.c:(.text+0x43c): undefined reference to `mosquitto_client_username'
collect2: error: ld returned 1 exit status

This is with mosquitto version 1.6.4

Here is my go env:
go env
GOARCH="arm"
GOBIN=""
GOCACHE="/home/odroid/.cache/go-build"
GOEXE=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/odroid/go"
GORACE=""
GOROOT="/usr/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_arm"
GCCGO="gccgo"
GOARM="6"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-I/usr/local/include -fPIC"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-shared"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build292861759=/tmp/go-build -gno-record-gcc-switches"

Here is the mosquitto libs:
ls -al /usr/local/lib/
total 1572
drwxr-xr-x  5 root root     4096 Aug 17 05:19 .
drwxr-xr-x 10 root root     4096 Jul 13  2016 ..
-rwxr-xr-x  1 root root  1014964 Aug 17 05:19 libmosquitto.a
lrwxrwxrwx  1 root root       17 Aug 17 05:19 libmosquitto.so -> libmosquitto.so.1
-rwxr-xr-x  1 root root   520840 Aug 17 05:19 libmosquitto.so.1
-rwxr-xr-x  1 root root    20400 Aug 17 05:19 libmosquittopp.a
lrwxrwxrwx  1 root root       19 Aug 17 05:19 libmosquittopp.so -> libmosquittopp.so.1
-rwxr-xr-x  1 root root    27540 Aug 17 05:19 libmosquittopp.so.1

And the includes:
ls -al /usr/local/include/
total 152
drwxr-xr-x  2 root root   4096 Aug 17 05:19 .
drwxr-xr-x 10 root root   4096 Jul 13  2016 ..
-rwxr-xr-x  1 root root 116034 Aug 17 05:19 mosquitto.h
-rwxr-xr-x  1 root root   4382 Aug 17 05:19 mosquitto_broker.h
-rwxr-xr-x  1 root root  11617 Aug 17 05:19 mosquitto_plugin.h
-rwxr-xr-x  1 root root   5949 Aug 17 05:19 mosquittopp.h

$ldconfig -v | grep mosquitto
	libmosquittopp.so.1 -> libmosquittopp.so.1
	libmosquitto.so.1 -> libmosquitto.so.1

I built it on Fedora30 yesterday with no problems. 
Any hints on why it can't find the shared libs would be most welcome.

Thanks for your help.

James

**Comment by iegomez** [comment]
That usually means you forgot the exports before building, i.e., run this before `make`:
```
export CGO_CFLAGS="-I/usr/local/include -fPIC"
export CGO_LDFLAGS="-shared"
```

**Comment by iegomez** [comment]
I don't have an Odroid C2 to try it and the necessary flags seem to be set, so I don't know what's wrong. My best guess is that the flags aren't getting picked up by the running terminal (but I have no idea why would that even happen), so maybe exporting them before does the trick?
```
export CGO_CFLAGS="-I/usr/local/include -fPIC"
export CGO_LDFLAGS="-shared"
make
```
I honestly don't know what could be the problem, but hopefully you can fix it and tell us later in case anyone else stumbles upon it.

**Comment by iegomez** [comment]
Since there was no feedback on this, I'll close it.
