### ISSUE TITLE
MongoDB is broken in test Docker image

### ISSUE THREAD

**Issue by iegomez** [iegomez/mosquitto-go-auth#296]
See https://github.com/iegomez/mosquitto-go-auth/actions/runs/6406162396/job/17390208682

**Comment by irfanazam1** [comment]
I have a fix this. If you merge my previous PR then I will submit another one with the fix.

**Comment by iegomez** [comment]
Sorry, I've been quite busy, but it was merged: https://github.com/iegomez/mosquitto-go-auth/pull/297

**Comment by iegomez** [comment]
Seemed harmless, but I'm curious about the connection though.

**Comment by mbv** [comment]
@iegomez Fix: https://github.com/iegomez/mosquitto-go-auth/pull/315
