### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by zcxzcxczcx** [iegomez/mosquitto-go-auth#3]
hi,could you please give us more introductions about this plugin.Now I could not run it exactly,but there are little ducuments to find.

**Comment by iegomez** [comment]
Hi! Documentation for configuring the plugin is available at the readme, but I'd be glad to guide you on installing or using it. 

What have you done already and what issues are you facing? It'd be great if you could share any error logs and configurations (just omit or mock the sensitive parts, such as DB credentials).

**Comment by zcxzcxczcx** [comment]
Firstly,Thank you very much that you can guide me.
Now I am facing the issue is that there is  authorization  for a user in a topic,but the user still denied by the mosquitto service for the topic

**Comment by iegomez** [comment]
Which backend(s) are you using (just regular files or something else)? Did you register them correctly?

If you share your mosquitto configuration (usually /etc/mosquitto/mosquitto.conf, and anything under /etc/mosquitto/conf.d/, depending on your configuration), and your password and acls files if you are using the Files backend (again, probably located at something like /etc/mosquitto/auth-plugin/acls and  /etc/mosquitto/auth-plugin/passwords, but it depends on your settings), I'll be able to help you make it work.

**Comment by zcxzcxczcx** [comment]
I am using mysql as backend.And I have complemented Authentication function in the test_user table.
Belowing are my register information（I use the secret  word to instead of true info,I can ensure these infos are correct ）:
auth_plugin /etc/mosquitto/go-auth.so
auth_opt_backends mysql
auth_opt_log_level debug
auth_opt_mysql_host secret
auth_opt_mysql_port 3306
auth_opt_mysql_user 保密
auth_opt_mysql_password 保密
auth_opt_mysql_dbname acl_test
auth_opt_mysql_userquery select password_hash from test_user where username = ? limit 1
auth_opt_mysql_superquery select count(*) from test_user where username = ? and is_admin = 1
auth_opt_mysql_aclquery select topic from test_acl where（username = ?）and rw >= ?

**Comment by iegomez** [comment]
Hi, I've just pushed a little change that'll print some debug messages for Mysql checks, including ACL ones. Could you try running mosquitto manually (stop mosquitto service and then something like `sudo mosquitto /etc/mosquitto/mosquitto.conf`), ideally with redis cache turned off so (check the readme for cache instructions), so we can see what gets printed when checking the ACL for your failing user?

**Comment by iegomez** [comment]
@zcxzcxczcx Did you have any luck checking the debug messages?

**Comment by iegomez** [comment]
I'm closing this issue for now as it seems inactive. If you need to add anything about it, just comment here.
