### ISSUE TITLE
TARGETPLATFORM does not include linux/amd64 in Dockerfile

### ISSUE THREAD

**Issue by spencerfeng** [iegomez/mosquitto-go-auth#304]
Hi @iegomez,

I would like to build the docker image for linux/amd64 platform, but I noticed that TARGETPLATFORM does not include linux/amd64 in Dockerfile. 

How can I achieve it?

**Comment by iegomez** [comment]
I haven't checked on this for a very long while, but if I recall correctly it'll build for `linux/amd64` by default if you don't define a `TARGETPLATFORM`. That is, that arg is for cross compiling to other archs.

**Comment by spencerfeng** [comment]
Hi @iegomez, this is not an issue. We can close this.
