### ISSUE TITLE
Update/Fix dependencies with active vulnerabilities

### ISSUE THREAD

**Issue by guyse-michael** [iegomez/mosquitto-go-auth#313]
I've started to use this and love how easy it is to integrate with a backend.  However the fact that there are 6 high/medium active vulnerabilities within the project worries me.  I can see that there is a bot actively creating PRs to get these dependencies updated for a few months now, however it would be great if we could get them officially updated in a release.

**Comment by iegomez** [comment]
Hey, @guyse-michael. You're right, the problem is I need to fix the automated tests first and I haven't got the time to do so.
I'll try to fix them soon and then I'll merge all those PRs.
