### ISSUE TITLE
No authorization possible with a costum plug in

### ISSUE THREAD

**Issue by karlTGA** [iegomez/mosquitto-go-auth#33]
Hallo @iegomez ,

i try to write a auth plugin that based on oauth2 and I think i found a bug in the costum plugin integration. The function `CheckPluginAcl` seems to return every time a false. The answer of the checks doesnt matter.

https://github.com/iegomez/mosquitto-go-auth/blob/4fa788213f81d391b639ce1d48fb274652889be4/go-auth.go#L736

**Comment by iegomez** [comment]
You're absolutely right, I'll fix it right away and make a new release. Thanks for reporting it.

**Comment by iegomez** [comment]
I've just pushed the change so the checks now looks like this:
```go
//CheckPluginAuth checks that the plugin is not nil and returns the plugins auth response.
func CheckPluginAuth(username, password string) bool {
	if commonData.Plugin == nil {
		return false
	}
	return commonData.PGetUser(username, password)
}

//CheckPluginAcl checks that the plugin is not nil and returns the superuser/acl response.
func CheckPluginAcl(username, topic, clientid string, acc int) bool {
	if commonData.Plugin == nil {
		return false
	}
	//If superuser, authorize it.
	if commonData.PGetSuperuser(username) {
		return true
	}
	//Check against the plugin's check acl function.
	return commonData.PCheckAcl(username, topic, clientid, acc)
}
```
Could you confirm it works for you so I can release it?

**Comment by karlTGA** [comment]
Thank you for the fast reply and the fix. I've tested it and with this fix it work like a charm.

**Comment by iegomez** [comment]
Great, I'll make the release then. Thanks again for reporting this.
