### ISSUE TITLE
jwt no information is sent to the endpoints

### ISSUE THREAD

**Issue by Phoenix3232** [iegomez/mosquitto-go-auth#330]
I set up authorization via jwt, but no information is sent to the endpoints in the request, except for Bearer in the headers.

<img width="508" alt="image" src="https://github.com/user-attachments/assets/b06b1a44-1e3d-4f77-b27a-9d7f77cc9dd7">
<img width="854" alt="image" src="https://github.com/user-attachments/assets/47d1092e-5df3-4897-aeed-f65dbaa58b4a">

**Comment by iegomez** [comment]
Sorry but that's not enough to tell you anything about your issue, which I guess it's not related to the plugin but to whatever setup you have on your receiving end, so I'd advise to check that first.

**Comment by Phoenix3232** [comment]
I wrote a simple test script that writes the entire request ($_REQUEST) and the body of the php://input request to a file.
If I switch the JWT mode to HTTP mode, everything works correctly and I can see the request without changing the endpoint code.

**Comment by iegomez** [comment]
Sorry, but again, I don't see how I can help you here, I can't externally debug your issue.
Set the log level to debug, monitor http traffic, etc., and see what's going on.

**Comment by Phoenix3232** [comment]
An empty request comes in, there is no data in the request body, nor in POST\GET\PUT
If you switch to mode=HTTP, then everything works. The problem is definitely in mode=JWT

**Comment by iegomez** [comment]
An empty request could mean anything, e.g. a proxy is stripping it, I can't say anything from the description.
If you get some logs, I could do something; otherwise, it's on you to debug.

**Comment by iegomez** [comment]
Also, I'm assuming your issue is with the ACL endpoint, because if it's the user endpoint, then please check the readme:
```
*Important*: Please note that when using JWT, username and password are not needed, so for user and superuser check the backend will send an empty string or empty form values. On the other hand, all three cases will set the "authorization" header with the jwt token, which mosquitto will pass to the plugin as the regular "username" param.
```

**Comment by Phoenix3232** [comment]
No, the problem is with the ACL endpoint.
In jwt mode it receives an empty request, although in http mode it receives the correct json.
There are no restrictions on my part, just connect the empty request in jwt mode

**Comment by Phoenix3232** [comment]
I tried both the form and json options.
No difference.
I repeat that there is a script on the end station that writes all requests to it (GET, POST) + the request body to a file. In jwt mode, emptiness comes, and in http mode, everything is fine

**Comment by iegomez** [comment]
I understand that, but what do you want me to do without any logs or anything?

**Comment by Phoenix3232** [comment]
I sent you the endpoint given, in which it is worth writing the entire request to it into a file. It is empty.
Why does everything work in http mode, but in jwt mode nothing works on some endpoints and addresses?

Can you check the operation of your device in this mode yourself?
<img width="406" alt="image" src="https://github.com/user-attachments/assets/76cb941a-f1fd-4e24-bf1f-633f33e87367">

**Comment by Phoenix3232** [comment]
I showed you the endpoint log. What other logs could there be?
If the problem was on my side or in the endpoint, then the http mode wouldn't work either.

**Comment by iegomez** [comment]
Mosquitto + plugin logs, actual http traffic logs, something that gives information.
You can even add your own logs, recompile the plugin and see wht's getting sent.
You showed me an image with a bunch of `Array()` lines, that tells me nothing.

**Comment by iegomez** [comment]
@Phoenix3232 let me know if you get any logs or if you already resolved the problem to see if I keep this issue open or close it.
