### ISSUE TITLE
Backend register error: couldn't initialize jwt backend with error unknown JWT mode.

### ISSUE THREAD

**Issue by FraanCarmonaa** [iegomez/mosquitto-go-auth#331]
Hello, Im having trouble configuring the plugin and getting it to work with Mosquitto 2.0.18. 

After installing all the dependencies, compiling it, and moving the go-auth.so file to the Mosquitto directory, I get the following error when trying to start Mosquitto:
`
time="2024-08-22T06:49:42Z" level=warning msg="unknown or empty hasher, defaulting to PBKDF2"
time="2024-08-22T06:49:42Z" level=fatal msg="Backend register error: couldn't initialize jwt backend with error unknown JWT mode."
time="2024-08-22T06:49:42Z" level=warning msg="unknown or empty hasher, defaulting to PBKDF2"
time="2024-08-22T06:49:42Z" level=fatal msg="Backend register error: couldn't initialize jwt backend with error unknown JWT mode."
time="2024-08-22T06:49:43Z" level=warning msg="unknown or empty hasher, defaulting to PBKDF2"
time="2024-08-22T06:49:43Z" level=fatal msg="Backend register error: couldn't initialize jwt backend with error unknown JWT mode."
time="2024-08-22T06:49:43Z" level=warning msg="unknown or empty hasher, defaulting to PBKDF2"
time="2024-08-22T06:49:43Z" level=fatal msg="Backend register error: couldn't initialize jwt backend with error unknown JWT mode."
time="2024-08-22T06:49:43Z" level=warning msg="unknown or empty hasher, defaulting to PBKDF2"
time="2024-08-22T06:49:43Z" level=fatal msg="Backend register error: couldn't initialize jwt backend with error unknown JWT mode."
`

The problem occurs when trying to use JWT as the backend; if I change it to files, there is no issue. I’m including my Mosquitto configuration with the plugin in case you could help me:
`
listener 8091
protocol websockets
cafile /etc/mosquitto/certs/chain.pem
certfile /etc/mosquitto/certs/fullchain.pem
keyfile /etc/mosquitto/certs/privkey.pem
require_certificate false
allow_anonymous false

auth_plugin /usr/lib/mosquitto/go-auth.so
auth_opt_backends jwt

auth_opt_log_level debug
auth_opt_log_dest file
auth_opt_log_file /var/log/mosquitto/mosquitto.log

auth_opt_jwt_algorithm RS256
auth_opt_jwt_key /etc/mosquitto/certs/jwt_public_key.pem
`

**Comment by iegomez** [comment]
You're missing the mode, it's the first param mentiuoned here and it's mandatory: https://github.com/iegomez/mosquitto-go-auth?tab=readme-ov-file#jwt

**Comment by iegomez** [comment]
In fact, there are no `auth_opt_jwt_algorithm` nor `auth_opt_jwt_key` options.
Please the Readme, I'm not sure what you're trying to do.

**Comment by FraanCarmonaa** [comment]
Thank you for your response. You are absolutely right, I apologize for that. I started by trying to configure it following the guide from the repo, but after skipping the initial command you mentioned about the mode and logically encountering the error, I began searching frantically on the internet and ended up creating a 'Frankenstein' of a configuration, without reasoning and understanding what I was doing.

I’ve been reassembling the .conf to verify the tokens from my Node.js server and I finally have this configuration:
`listener 8091
protocol websockets
cafile /etc/mosquitto/certs/chain.pem
certfile /etc/mosquitto/certs/fullchain.pem
keyfile /etc/mosquitto/certs/privkey.pem
#require_certificate false
#allow_anonymous false

plugin /usr/lib/mosquitto/go-auth.so
auth_opt_backends jwt

# JWT Configuration
auth_opt_jwt_mode remote
auth_opt_jwt_host petsys.es
auth_opt_jwt_with_tls true
auth_opt_jwt_port 443
auth_opt_jwt_getuser_uri /auth/verify-token
auth_opt_jwt_aclcheck_uri /auth/check-acl

auth_opt_jwt_params_mode json
auth_opt_jwt_response_mode json

auth_opt_log_level trace
auth_opt_log_dest file
auth_opt_log_file /var/log/mosquitto/mosquitto.log
`
With this configuration, I can start Mosquitto correctly.

I wanted to ask if you think any configuration parameters might be missing, as now when I try to test the connection with Mosquitto Websockets through MqttExplorer, sending the token as the user and leaving the password empty, I get an 'Unauthorized' error. However, there is no log of calls to my backend endpoints which are the ones that verify the token and return a 2XX or 4XX status based on its validity, so I don’t understand the origin of the 'Unauthorized' error since it’s not consulting the backend endpoints.

I tried configuring Mosquitto logs for more detail on this, but all it returns in mosquitto.log is: '1724392776: Sending CONNACK to mqtt-websocket (0, 5)', and I have no way of knowing what might be happening to continue debugging.

Once again, thank you very much for your help.

**Comment by FraanCarmonaa** [comment]
okay forget it, after some hours debugging i finally make it working like a charm!

Thanks for your instructions!
