### ISSUE TITLE
JWT Plugin checked on All Mosquitto Ports

### ISSUE THREAD

**Issue by FraanCarmonaa** [iegomez/mosquitto-go-auth#334]
Hi! 
I have a generic question about the plugin itself (sorry if I’m not approaching this correctly): I configured the plugin to work with the JWT backend from an Angular app to the broker through port 8091, which works correctly, checking the specific endpoints for ACL, superuser, and verify-token.

I have another port enabled on Mosquitto, which handles authentication via certificates (without JWT). However, I notice that every time a device connects to port 8883 with certificates, the plugin ‘activates’ and redirects to the API endpoints to verify the token, ACL, and superuser. I understand that the plugin should not be activated for port 8883, which is not configured for or using tokens in its connections (sorry if I’m mistaken or didn’t understand correctly).

The question is: Shouldn’t the plugin with the JWT backend be activated only on the configured port?

I’m attaching my mosquitto.conf in case it might be helpful:
`#Global Settings
log_type all
log_dest file /var/log/mosquitto/mosquitto.log
connection_messages true
log_timestamp true

#General security settings 
tls_version tlsv1.2

#Listener 8883 - TLS with Certificates Only
listener 8883
cafile /etc/mosquitto/certs/chain.pem
certfile /etc/mosquitto/certs/fullchain.pem
keyfile /etc/mosquitto/certs/privkey.pem
require_certificate true
allow_anonymous false
use_identity_as_username true

#Other configurations specific to this listener
max_connections 1000
max_inflight_messages 1000
max_queued_messages 1000

#Listener 8091 with mosquitto-plugin
listener 8091
protocol websockets
cafile /etc/mosquitto/certs/chain.pem # (Put these certs lines to make it works without certs on the angular mqtt connections, if i delete these lines, angular mqtt connections fails)
certfile /etc/mosquitto/certs/fullchain.pem # (Put these certs lines to make it works without certs on the angular mqtt connections, if i delete these lines, angular mqtt connections fails)
keyfile /etc/mosquitto/certs/privkey.pem # (Put these certs lines to make it works without certs on the angular mqtt connections, if i delete these lines, angular mqtt connections fails)
require_certificate false
allow_anonymous false
max_connections 1000

plugin /usr/lib/mosquitto/go-auth.so
auth_opt_backends jwt

#JWT Configuration
auth_opt_jwt_mode remote
auth_opt_jwt_host my_host
auth_opt_jwt_with_tls true
auth_opt_jwt_port 443
auth_opt_jwt_getuser_uri /auth/verify-token
auth_opt_jwt_aclcheck_uri /auth/check-acl
auth_opt_jwt_superuser_uri /auth/check-super-user

auth_opt_jwt_params_mode json
auth_opt_jwt_response_mode status

auth_opt_log_level all
auth_opt_log_dest file
auth_opt_log_file /var/log/mosquitto/mosquitto.log

#Cache Configuration
auth_opt_cache true
auth_opt_cache_type go-cache

auth_opt_cache_reset true
auth_opt_cache_refresh true

auth_opt_auth_cache_seconds 30
auth_opt_acl_cache_seconds 30

auth_opt_auth_jitter_seconds 3
auth_opt_acl_jitter_seconds 3
`

Thanks in advance

**Comment by iegomez** [comment]
I think you just need to set `per_listener_settings` option to `true` so options aren't shared among listeners.
This is a Mosquitto thing though, not coming from the plugin. It's defined here https://mosquitto.org/man/mosquitto-conf-5.html:

> per_listener_settings [ true | false ]
> If true, then authentication and access control settings will be controlled on a per-listener basis. The following options are affected:
> 
> password_file, acl_file, psk_file, allow_anonymous, allow_zero_length_clientid, auto_id_prefix.
> 
> plugin, plugin_opt_*,
> Note that if set to true, then a durable client (i.e. with clean session set to false) that has disconnected will use the ACL settings defined for the listener that it was most recently connected to.
> 
> The default behaviour is for this to be set to false, which maintains the settings behaviour from previous versions of mosquitto.
> 
> Reloaded on reload signal.

**Comment by FraanCarmonaa** [comment]
Resolved and working! Thank you very much for your help.

I would like to ask you one last question about MQTT in general as I am facing a problem and cannot find help anywhere, and would be happy to know about your opinion on the situation I'm dealing with:

I need to establish an MQTT connection over WebSockets from Arduino with a JWT (added in memory) to port 8091 (configured with your plugin to check the token). Once established, I have a certificate generation and automatic download system on the Arduino (I use this first connection over port 8091 with JWT for pairing and certificate download on the Arduino). However, I currently cannot establish that initial WebSocket connection on port 8091 without certificates, and it's driving me crazy.

Do you have any ideas on how to approach this initial pairing of Arduino that needs to establish a first connection to execute the entire certificate generation cycle?

This is clearly a question unrelated to the issue you helped me resolve, which I will mark as resolved. I apologize for this additional question, but I've been stuck for days trying to deal with a solution to solve the problem.

Thank you very much for your help!

**Comment by iegomez** [comment]
Hard to tell without deeper knowledge of your setup, but I don't see how'd you go about establishing a connection that enforces use of a cert before bootstrapping it in some other fashion. So sorry, I don't have any obvious suggestion.

**Comment by FraanCarmonaa** [comment]
Dont worry, you already helped me a lot. Thanks!
