### ISSUE TITLE
build always failed on "go-auth.h" No-Such File

### ISSUE THREAD

**Issue by dvn01** [iegomez/mosquitto-go-auth#34]
Hi Ignacio,

First thanks for the new plugin, I have being using JPMens auth plugin for a while now however that doesn't seems to work with newer versions of mosquitto.

You'll have to forgive now, because I am neither a linux or go developer. Because of project constraints I don't have time to sit a learn really learn both, so hopefully you can help me out.

I am running on Amazon Linux 2 AMI centos image.

I have installed mosquitto.1.6.7 and created a service which is running (currently using pwfile for testing).

I installed go, here is the go-env output:

```
ec2-user@ip-172-27-0-231:~$ go version
go version go1.13.1 linux/amd64
ec2-user@ip-172-27-0-231:~$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ec2-user/.cache/go-build"
GOENV="/home/ec2-user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ec2-user/mqtt167/mosquitto-go-auth"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-I/usr/local/include -fPIC"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-shared"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build003155464=/tmp/go-build -gno-record-gcc-switches"

```

installed your plugin via github 
git clone https://github.com/iegomez/mosquitto-go-auth.git

```
cd mosquitto-go-auth
make
```

I get the following error

> go build -buildmode=c-archive go-auth.go
> $GOPATH/go.mod exists but should not
> make: *** [all] Error 1

I tried different workarounds no luck.
################################################################
Next i uninstalled the plugin folder and ran the following command

`go get https://github.com/iegomez/mosquitto-go-auth`

which produced the following error:

> auth-plugin.c:11:10: fatal error: go-auth.h: No such file or directory
>  #include "go-auth.h"
>           ^~~~~~~~~~~
> compilation terminated.

As you can probably I just swinging and missing at this stage, so any help would be greatly appreciated. 

Thanks you.

**Comment by dvn01** [comment]
Wow quick replay, 

Thanks again and no problem as least I know which path to take.

Cheers.

**Comment by dvn01** [comment]
Hi Ignacio,

I couldn't figure out the issue with the Go paths and needed to get the broker up and running, so I just reconfigure the JPMens pluging and mosquitto 1.5.9.

Thank anyways.

**Comment by iegomez** [comment]
I'm sorry it didn't work for you. If you ever want to give it another try and can supply more details on any possible errors, just reopen the issue and I'll try to help wherever I can.
