### ISSUE TITLE
Debian support

### ISSUE THREAD

**Issue by wildstray** [iegomez/mosquitto-go-auth#39]
Hello, we're using go-auth in replacement of archived project mosquitto-auth-plugin. We strongly rely on Debian installation (and for mosquitto-go-auth there was the deb package) so I think one of the only missing feature of this project is Debian support.
I forked your repository and I'm working on it, I'll submit a PR soon but I'll happier if somebod else can/want contribute. I find two issue in this process:
1) Changed API from 1.4 to 1.5 and the need for accessory functions (eg. mosquitto_client_id and mosquitto_client_username). It cannot compile because these funcions are not exported in mosquitto-dev Debian package. The only pragmatic solution I find is a patch to bypass that functions (for 1.5) and use internal structures. In this way it compile and run, but the requirement is to have the sources of mosquitto package already patched and configured (eg. apt-get source mosquitto) but the dipendence from another source is not a canonical procedure (and I cannot find other solutions).
2) I had to disable test cases because all test are executed independently from the lack or presence of external database and if it was previously configured to pass the tests or not. So in an environment without mongodb and/or mysql and/or postgresql part of tests will always fails (and have to wait for a long time to timeout).
3) Not sure about version number (to be agreed with you, in my tests I used 0.6.1-1), package maintainer, etc.

**Comment by iegomez** [comment]
Hi! I hadn't thought about distributing a deb package (or any other) because I find building the plugin pretty straightforward, but if you want to contribute I'll be happy to review that PR.

**Comment by wildstray** [comment]
Hi, I submitter the PR...

**Comment by iegomez** [comment]
Sorry, I've been a bit busy, I'll try to look at it tomorrow.

**Comment by iegomez** [comment]
Hey, I'm closing this issue, we can continue any discussion on the PR.
