### ISSUE TITLE
Question - clientid not sent to login ?

### ISSUE THREAD

**Issue by aldobongio** [iegomez/mosquitto-go-auth#48]
Hi, is there a specific motivation (maybe Mosquitto is enforcing it) behind the fact that the HTTP plugin passes as parameter the clientId only when invoking the "acl" method ? Why the "login" method is prevented from receiving the clientid ?

**Comment by iegomez** [comment]
Indeed `mosquitto` didn't use to pass the `clientid` through `mosquitto_auth_unpwd_check`, while it did on `mosquitto_auth_acl_check`, but now both receive a pointer to the `client` struct. So it seems like it's definitely possible to extract the `clientid` from that and pass it along in the backends, but this needs checking, as `acl` checks get the user name from this struct, while `auth` checks get it directly, so it may be possible that the `clientid` isn't populated for the latter. 

In any case, what would be the use case for this?

**Comment by aldobongio** [comment]
Hi, thanks for the detailed explanation. 
A possible use case would be keeping track, on the HTTP backend, of username/clientid combinations or of the only clientid requests for monitoring. For instance if two devices by accident are configured with the same clientid and connect with the 'autoreconnect' flag the MQTT broker will continously kick off one and then the other, and they will continously try to reconnect thanks to the autoreconnect flag. Keeping track of the rate of each clientid on the login method permit to raise some kind of alarm about the misconfiguration. 

Another use case is a device configured correctly configured with its own unique clientid but performing a full connect + publish + disconnect for sending each measure, instead of staying connected (with keep-alive) for long time. Just using the 'username' for measuring the login rate sometime is not applicable because in real scenarios we have multiple devices sharing the same username and thus an high rate of logins by username could be legit, whereas a an high rate of logins by clientid could signal the connect+publish+disconnect antipattern.

Thanks again for the help and keep up the great work on your plugin!

**Comment by iegomez** [comment]
Sounds fair. As mentioned, I'll have to take a look first and if the `clientid` is passable, then I'll add it to ACL checks next week.

**Comment by iegomez** [comment]
Hey @aldobongio , sorry I haven't implemented this yet, I had a pretty busy week. 
Anyway, I got some little time today to start a new branch and make some changes leading to the `clientid` being passed and hope it'll be done by Monday or Tuesday. Would you be able to test that branch when I finally push it?

**Comment by aldobongio** [comment]
Sure, I will be happy to test it.
Thanks!

**Comment by iegomez** [comment]
Hey, just wanted to let you know that I have a few thing going on these days so I'm pushing this to next week. Sorry for the inconvenience.

**Comment by iegomez** [comment]
@aldobongio I'm terribly sorry for the time it took me, but I'm happy to announce that I finally got the change done. I already merged it to master, but you may check all changes in this PR: https://github.com/iegomez/mosquitto-go-auth/pull/52.

Please let me know if there's any issue or something I missed.

**Comment by aldobongio** [comment]
I will try it the next week and I will let you know if it works.

Thanks again!

**Comment by aldobongio** [comment]
Hi, finally I checked the HTTP authentication: clientid was correctly sent on login.
So the issue can be closed.

Thanks!
