### ISSUE TITLE
How to uncheck the superusers

### ISSUE THREAD

**Issue by alochym01** [iegomez/mosquitto-go-auth#49]
Hi all

is there any option to uncheck username start with S character

# Usernames with this fnmatch(3) (a.k.a glob(3))  pattern are exempt from the
# module's ACL checking
auth_opt_superusers S*

thank you

**Comment by iegomez** [comment]
Hi.  I'm not sure what you are asking here, so could you explain this a little better?

**Comment by alochym01** [comment]
hi @iegomez 
from the https://github.com/jpmens/mosquitto-auth-plug
there is an option to uncheck authentication  for superuser start with S* in mosquitto config file 

https://github.com/jpmens/mosquitto-auth-plug/blob/master/examples/mosquitto-mysql.conf

how i can do it in mosquitto-go-auth plugin

thank you

**Comment by iegomez** [comment]
Ok, from that link I get that users following the `S*` pattern don't need to be checked against ACLs even if they don't satisfy the `auth_opt_superquery`. This is not supported in this plugin.

**Comment by alochym01** [comment]
thank you
