### ISSUE TITLE
Build from source is not working - undefined: plErr/ipErr/gErr/bErr

### ISSUE THREAD

**Issue by aldobongio** [iegomez/mosquitto-go-auth#55]
Trying to build the current master (commit_id: `d53b09a41d38209781645ed9b9a62838823ffde3`) the process fails with a go error.
Trying instead to build the commit associated with #52 (commit_id: `0e39a99963755636a20ce54b973d4892cad66248`) it works.

The error is the following, it seems related to #53:
```
./go-auth.go:178:52: undefined: plErr
./go-auth.go:186:58: undefined: plErr
./go-auth.go:195:45: undefined: ipErr
./go-auth.go:205:61: undefined: gErr
./go-auth.go:273:98: undefined: bErr
./go-auth.go:281:98: undefined: bErr
./go-auth.go:289:98: undefined: bErr
./go-auth.go:297:98: undefined: bErr
./go-auth.go:305:98: undefined: bErr
./go-auth.go:313:98: undefined: bErr
./go-auth.go:313:98: too many errors
make: *** [Makefile:2: all] Error 2
```

**Comment by iegomez** [comment]
Oops, sorry about that, I didn't commit some changes when refactoring. It's fixed now.
