### ISSUE TITLE
How to restrict the user for read-only(SUB) using mosquitto-go-auth with postgres DB?

### ISSUE THREAD

**Issue by vvksahoo** [iegomez/mosquitto-go-auth#56]
I am trying to configure postgres DB with mosquitto-go-auth . 
```Configuration in go-auth.conf
auth_plugin /mosquitto/go-auth.so

auth_opt_log_level debug
auth_opt_backends postgres
auth_opt_check_prefix false


auth_opt_pg_host postgres
auth_opt_pg_port 5432
auth_opt_pg_dbname mqtt_auth
auth_opt_pg_user admin
auth_opt_pg_password password
auth_opt_pg_userquery select password_hash from test_user where username = $1 and is_admin = true limit 1
auth_opt_pg_aclquery select topic from test_acl where username = $1 AND (rw=$2 or rw=3)
```
With this configuration :
What's working : 
- Particular user can publish on particular topic(which is mentioned on DB column aslo) , basically read-only is happening .
- Particular user can publish on particular topic and subscribe to that particular topic also , basically read-write is happening .
What's not working : I want to define a user which can only be subscribe to a particular topic and cant publish to that topic , basically write-only .
``` DB table:
 id | username |    topic    | rw
----+----------+-------------+----
  1 | Jack         | test/user/#       | 2
  3 | jhon         | house/second |  3
  2 | Rock        |  floor/temp      |  1
```
I want 'Rock' only can subscribe to 'floor/temp' , shouldn't  have right to publish. But with this configuration it is allowing Rock to publish , i dont want to happen that , so let me know  what i am doing here .

**Comment by iegomez** [comment]
Hey, for starters you're mixing things up: publishing isn't reading but writing (and subscribing is _like_ reading, not writing).

That said, these are the possible `acc` values:
```
#define MOSQ_ACL_NONE 0x00
#define MOSQ_ACL_READ 0x01
#define MOSQ_ACL_WRITE 0x02
#define MOSQ_ACL_SUBSCRIBE 0x04
```
Read/Write is also supported with `acc` 3 for compatibility. 

So from your example the user **shouldn't be allowed to publish** and if he's being granted permission to do so there's some other problem going on (maybe it's a superuser, another plugin is authorizing it, etc.). I'd suggest to set the log level to `debug` and pull the logs to see what's going on.

On another note, please check https://github.com/iegomez/mosquitto-go-auth/issues/46 and https://github.com/iegomez/mosquitto-go-auth/issues/18 for details on `MOSQ_ACL_SUBSCRIBE`, which may be needed depending on your Mosquitto version.

**Comment by vvksahoo** [comment]
Thank you so much for your response , will update here soon.

**Comment by iegomez** [comment]
Hey, @vvksahoo, any updates on this?

**Comment by iegomez** [comment]
I'll close this for now but please open a new issue with details if you're still facing this or other issues.
