### ISSUE TITLE
 auth error: sasl conversation error: unable to authenticate using mechanism \"SCRAM-SHA-1\": Authentication failed.

### ISSUE THREAD

**Issue by IsabelManiega** [iegomez/mosquitto-go-auth#57]
Hi,
I have an issue when I check the connection with mongoDB in mosquitto.

My configuration is described as follows:

# mosquitto.conf:
pid_file /var/run/mosquitto.pid

persistence true
persistence_location /var/lib/mosquitto/

log_dest file /var/log/mosquitto/mosquitto.log
log_type all

include_dir /etc/mosquitto/conf.d

# /etc/mosquitto/conf.d/mosquitto-go-auth.conf:

auth_plugin /var/mosquitto-go-auth/go-auth.so
auth_opt_backends mongo
auth_opt_check_prefix false
allow_anonymous false

*debug
auth_opt_log_level debug

*MongoDB:
auth_opt_mongo_host localhost
auth_opt_mongo_port 27017
auth_opt_mongo_dbname mosquitto
auth_opt_mongo_username mosquitto 
auth_opt_mongo_password mosquitto_auth
auth_opt_mongo_users users
auth_opt_mongo_acls acls

I check it with:
# mosquitto_pub -h localhost -p 1883 -u user -P 1234.pass -t 'test' -m 'hola'
Connection error: Connection Refused: not authorised.

# journalctl -u mosquitto -f -n 50

abr 01 15:39:14 debian Mosquitto[420]: time="2020-04-01T15:39:14+02:00" level=debug msg="Mongo get user error: connection() : auth error: sasl conversation error: unable to authenticate using mechanism \"SCRAM-SHA-1\": Authentication failed

# sudo tail -f mosquitto.log
1585748345: Config loaded from /etc/mosquitto/mosquitto.conf.
1585748345: Loading plugin: /var/mosquitto-go-auth/go-auth.so
1585748345:  ├── Username/password checking enabled.
1585748345:  ├── TLS-PSK checking enabled.
1585748345:  └── Extended authentication not enabled.
1585748345: Opening ipv4 listen socket on port 1883.
1585748345: Error: Address already in use
1585748014: Sending CONNACK to ::1 (0, 5)
1585748014: Socket error on client <unknown>, disconnecting.
1585748354: New connection from ::1 on port 1883.

where is the problem??

**Comment by iegomez** [comment]
Hi, I'm not sure about this, I'll take a look as soon as I get the time. In the meantime please check this issue (https://github.com/iegomez/mosquitto-go-auth/issues/43) and PR (https://github.com/iegomez/mosquitto-go-auth/pull/44) to see if they could be related.

**Comment by IsabelManiega** [comment]
Hi!, 
Yes I think that the problem is the same (#43).
I have changed mongo.go and generated the plugin, but I have a problem:
![image](https://user-images.githubusercontent.com/25103614/78331302-0b11ba00-7586-11ea-909c-bb606a2858ae.png)

Is it necessary some change more?
sorry, I didn't develop code in golang.

Thanks a lot

**Comment by iegomez** [comment]
I introduced `clientid` for the `GetUser` method in this commit: https://github.com/iegomez/mosquitto-go-auth/commit/0e39a99963755636a20ce54b973d4892cad66248
The code you're looking at to implement the changes for MongoDB doesn't consider this, so just make sure to check my commit to keep the method signature correct.

**Comment by IsabelManiega** [comment]
Thanks ! I obtained go-auth.so!
My change is here: https://github.com/IsabelManiega/mosquitto-go-auth.

**Comment by iegomez** [comment]
Great! I haven't merged the changes because I'm waiting on some tests from Chris to ensure everything works, but it'll get to master soon.

**Comment by iegomez** [comment]
Changes were merged so I'll close this one for now. Thanks again for reporting!
