### ISSUE TITLE
how to use plugin

### ISSUE THREAD

**Issue by pumper** [iegomez/mosquitto-go-auth#58]
hi,could you please give us more introductions about this plugin.Now I could not run it exactly,but there are little ducuments to find.
I build it successfully and connect it to mysql backend. 
now i have to build password with pw and inert it into the database to work. how can I put it in my java application to manage it automatically?

**Comment by pumper** [comment]
every time i restart mosquitto the only log that is inserted in the log file is :
time="2020-04-20T16:21:35+04:30" level=info msg="Backend registered: Mysql"
time="2020-04-20T16:21:35+04:30" level=info msg="No cache set."
time="2020-04-20T16:21:54+04:30" level=info msg="Cleaning up plugin"
time="2020-04-20T16:22:02+04:30" level=info msg="Backend registered: Mysql"
time="2020-04-20T16:22:02+04:30" level=info msg="No cache set."
time="2020-04-20T16:24:31+04:30" level=info msg="Backend registered: Mysql"
time="2020-04-20T16:24:31+04:30" level=info msg="No cache set."
time="2020-04-20T16:39:25+04:30" level=info msg="Cleaning up plugin"
time="2020-04-20T16:39:25+04:30" level=info msg="Backend registered: Mysql"
time="2020-04-20T16:39:25+04:30" level=info msg="No cache set."

**Comment by iegomez** [comment]
Hey! I'll need some more details on what you wanna do and what have you tried already.

**Comment by pumper** [comment]
so far I created password hash using:
MessageDigest digest = MessageDigest.getInstance("SHA-256");
byte[] hash = digest.digest(password.getBytes(StandardCharsets.UTF_8));
but when I try to login I get
 level=error msg="invalid PBKDF2 hash supplied"
in my logs

**Comment by pumper** [comment]
I also tried this one with no luck:
SecureRandom random = new SecureRandom();
			byte[] salt = new byte[16];
			random.nextBytes(salt);
			KeySpec spec = new PBEKeySpec(password.toCharArray(), salt, 10000, 256);
			SecretKeyFactory factory = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256");
			byte[] hash = factory.generateSecret(spec).getEncoded();

**Comment by iegomez** [comment]
I haven't tried PBKDF2 in Java, so I'd suggest creating some dummy program to see how a password generated from Java and the one from the `pw` compare. By the way, how are you building the password with `pw`?

**Comment by pumper** [comment]
I use it in linux shell
./pw -a sha256 -p password

**Comment by iegomez** [comment]
That looks ok.

**Comment by pumper** [comment]
please dont close issue if i found the solution I put it here or maybe someone else do it

**Comment by pumper** [comment]
I tested plugin and it works well. the only thing that I must mention is that if the user is not Superuser and we want that user have R/W rights for some topic the rw param must be 7 not 3 please modify README.

**Comment by pumper** [comment]
and in java if you want to generate  correct hash you must do it this way:

`
String createPasswordHash(String password) {
		StringBuilder sb=new StringBuilder();
		try {
			SecureRandom random = new SecureRandom();
			byte[] salt = new byte[16];
			random.nextBytes(salt);
			System.out.println(salt.toString());
			KeySpec spec = new PBEKeySpec(password .toCharArray(), salt, 100000, 256);
			SecretKeyFactory factory;
			factory = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256");
			byte[] hash = factory.generateSecret(spec).getEncoded();
			
			sb.append("PBKDF2$").
			append("sha256$").append("100000$").append(Base64.getEncoder().encodeToString(salt)).
			append("$").
			append(Base64.getEncoder().encodeToString(hash));
		} catch (NoSuchAlgorithmException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (InvalidKeySpecException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return sb.toString();
		
		
	}


`

**Comment by iegomez** [comment]
Edited your comment to format the code, thanks for the example!

> I tested plugin and it works well. the only thing that I must mention is that if the user is not Superuser and we want that user have R/W rights for some topic the rw param must be 7 not 3 please modify README.

That's not exactly true. The thing is mosquitto offers this `acc` values:
```
#define MOSQ_ACL_NONE 0x00
#define MOSQ_ACL_READ 0x01
#define MOSQ_ACL_WRITE 0x02
#define MOSQ_ACL_SUBSCRIBE 0x04
```
An MQTT client could either use `4` or not to subscribe before reading, it seems many of them do. So if you only set an ACL for `1`, then on subscription the client will fail to subscribe and do whatever it is that specific client does with that info (disconnect? blacklist the topic? dismiss it?). So if you wanna ensure a client is able to subscribe and read from a topic, then you must account for both `1` and `4` for the `acc` value. How you do that is an implementation detail, since you may have specific topic ACLs, you may have a general query that does some checking, etc.
