### ISSUE TITLE
Documentation on how it works

### ISSUE THREAD

**Issue by gusseleet** [iegomez/mosquitto-go-auth#6]
I don't really understand how the plugin works.

When and how is the postgres queries executed? Lets say "select password_hash from "user" where username = $1 and is_active = true limit 1".  Is this plugin purly for limiting users when subbing to a topic via MQTT?

**Comment by iegomez** [comment]
I left an answer at the original post in the loraserver forum: https://forum.loraserver.io/t/filter-messages-on-the-network-server-or-before/1163/5.

**Comment by iegomez** [comment]
I'm closing this issue so we can keep the discussion in the forum.
