### ISSUE TITLE
Http Status Check in JWT backend

### ISSUE THREAD

**Issue by marvin21** [iegomez/mosquitto-go-auth#61]
Hi,
I am using the JWT backend to authorize clients with OAuth2 tokens. The authorization backend is build with Spring. Actually, everything is running fine, but:

Is there any reason why the jwt backend is checking the resp.Status for "200 OK"? Would it not be sufficient to check the resp.StatusCode to be equal 200?
Why I am asking this: for any reason, the resp.Status in my case is always just "200" instead of "200 OK". So the backend fails to authorize a client, but the actual authorization is successful.
And in the logs, this error message appears: "Error code: 200"

This is the location, where my authorization fails:
![grafik](https://user-images.githubusercontent.com/9257620/81571530-5ba8de00-93a2-11ea-8be2-c2e769903a50.png)

**Comment by iegomez** [comment]
Hey, @marvin21, thanks for reporting this. I'll fix it as soon as I get some time.

**Comment by iegomez** [comment]
OK, here's the fix and additions to the docs: https://github.com/iegomez/mosquitto-go-auth/pull/62
Gonna merge it right away since it's a small change, but let me know if you find anything odd in the PR so I can fix it later on a following one (if not, just close the issue).
