### ISSUE TITLE
How to generate PBKDF2 hash password using Python which can verify by mosquitto-go-auth ?

### ISSUE THREAD

**Issue by vvksahoo** [iegomez/mosquitto-go-auth#65]
I am using mosquitto-go-auth for mqtt user authentication . In my case i have API for user which generate the PBKDF2 hash for given password. 
in python:
````
import hashlib
from os import urandom
from base64 import b64encode, b64decode


SALT_LENGTH = 16
HASH_FUNCTION = 'sha512'
COST_FACTOR = 100000


def make_hash(password):
    password = password.encode('utf-8')
    salt = b64encode(urandom(SALT_LENGTH))
    hash_key = b64encode(hashlib.pbkdf2_hmac(HASH_FUNCTION, password, salt, COST_FACTOR))
    return 'PBKDF2${}${}${}${}'.format(
        HASH_FUNCTION,
        COST_FACTOR,
        str(salt, 'utf-8'),
        str(hash_key, 'utf-8')
        )
print(make_hash("password"))
````
Whatever the hash password got, using same for connect to broker but got " Connection Refused: not authorised." How we can generate a hash password using python script which can verify by mosquitto-go-auth.

Thanks.

**Comment by iegomez** [comment]
Hey, this could be related to this PR: https://github.com/iegomez/mosquitto-go-auth/pull/45
That's gonna me merged today or tomorrow, so if you can wait a bit, that'd be great; if you're in a hurry, checkout that branch and see if that works for you and then you may go back to master once we merge it.

**Comment by vvksahoo** [comment]
i would like to wait until this PR get merge and pull the new docker image of it. please let me once its done. Same i will test and we will close this issue.

**Comment by iegomez** [comment]
@vvksahoo Just merged that PR so you may test it.

**Comment by vvksahoo** [comment]
With this latest release docker image version will be change ? Doing
docker-compose up, creating database in postgres
and keeping a PBKDF2 hash password and publishing with username and
password,  getting same error . Authentication failed.

**Comment by iegomez** [comment]
Mm... maybe you need to rebuild the image or something like that. I normally build everything and don't use docker, so I tend to forget if there's anything that's needed for it to work.
If rebuilding or building from source still don't work, then this was an unrelated issue and we'll need to start debugging things.

**Comment by vvksahoo** [comment]
@iegomez , i tried to re-image with root dockerfile , and used that image in docker-compose file but same error is coming after running.  Authentication failed.

**Comment by coldfire84** [comment]
> @iegomez , i tried to re-image with root dockerfile , and used that image in docker-compose file but same error is coming after running. Authentication failed.

Did you set the salt encoding in your config via the option outlined below (be sure to change `'<backend-name>'` to relevant backend):
```
auth_opt_<backend-name>_salt_encoding utf-8
```

**Comment by vvksahoo** [comment]
Thanks a lot @iegomez / @coldfire84 , its works for me.
