### ISSUE TITLE
MQTT Server crashes when it can't make conenction to the HTTP backend

### ISSUE THREAD

**Issue by ivica3730k** [iegomez/mosquitto-go-auth#68]
Plugin works as expected, but when you stop HTTP backend and another client tries to connect the MQTT the server crashes.

Provided screenshot shows first client auth normal as usual. Before authing the 2nd client my backend connection broke, so when 2nd client tried to connected server crashed. 

![gitissue](https://user-images.githubusercontent.com/17437897/82122081-4c9ea300-9789-11ea-93ee-1c56a596ea19.png)

Was able to reproduce this every time.

Not sure is it a issue or not. It might be better to just not authenticate the users if backend is not present.

**Comment by iegomez** [comment]
Thanks for reporting this, I'll take a look later today or at least during the week.

**Comment by iegomez** [comment]
Hey, @ivica3730k, I just merged this PR to fix your issue: https://github.com/iegomez/mosquitto-go-auth/pull/70
Could you give it a try and confirm that it works?

**Comment by ivica3730k** [comment]
Hello back!

Thank you for your time, I can now confirm that it does not crash, instead it just wont auth the connection.

 Just a one thing now, I am not sure how you imagined it, as currently, without backend clients which are subscribing to the topic are not getting kicked out, but that maybe is not even a issue as without auth noone can publish anything anyways. 

![image](https://user-images.githubusercontent.com/17437897/82719517-18ecdd00-9ca3-11ea-8f71-130b5f3ed54e.png)

First the subscribe method is shown, then the publish. As you can see, the client which is subscribing is not getting kicked out.

I will test how it works with the cache enabled and get back to you with the results!

Cheers!
IcE

**Comment by iegomez** [comment]
I'm glad to read that it's working!

As for disconnection, it's actually something that I need to give a better overall look to and haven't found the time to do it as you can see from this terribly described issue: https://github.com/iegomez/mosquitto-go-auth/issues/31

**Comment by ivica3730k** [comment]
Yep I see.

Thank you very much for your time.
I might learn some GO in the future :)

In my oppinion this can now be closed!
