### ISSUE TITLE
Cannot dynamically load executible

### ISSUE THREAD

**Issue by vincems** [iegomez/mosquitto-go-auth#8]
Hi folks,

I'm not sure if this is platform specific or I'd done something dumb.
Environment details:
  DISTRIB_ID=Ubuntu
  DISTRIB_RELEASE=16.04
  DISTRIB_CODENAME=xenial
  DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"

After a fresh compile of the latest release of the auth plug-in I'm getting an error
The original Makefile had the following:
        go build -buildmode=c-shared -o go-auth.so

but this results in an error:

  flag needs an argument: -o
  usage: build [-o output] [-i] [build flags] [packages]
  Run 'go help build' for details.

If I move the -o parameter to first in the line - it cleanly compiles but won't load due to the following:
```
1532398762: mosquitto version 1.4.15 (build date 2018-07-24 13:34:50+1200) starting
1532398762: Config loaded from /etc/mosquitto/mosquitto.conf.
1532398762: Error: Unable to load auth plugin "/usr/local/lib/go-auth.so".
1532398762: Load error: /usr/local/lib/go-auth.so: cannot dynamically load executable
```
libraries are all owned by the user mosquitto (but I don't think that's what the problem is here)

Can anyone help here ?

Thanks
   Vince.

**Comment by iegomez** [comment]
Hi!

What version of Go are you running? And did you run `make`or just tried `go build -buildmode=c-shared -o go-auth.so`on its own?

**Comment by vincems** [comment]
Thanks for getting back iegomez ... 

go version
go version go1.10.2 linux/amd64

Using the make directly from git resulted in:
make
```
go build -buildmode=c-archive go-auth.go
go build -buildmode=c-shared -o go-auth.so
flag needs an argument: -o
usage: build [-o output] [-i] [build flags] [packages]
Run 'go help build' for details.
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2
```

I have also tried manually running each command from the Make file - with the same result.

Tweaking the position of the -o argument results in a clean compile - but then the resultant .so won't load.

Cheers
  Vince.

**Comment by iegomez** [comment]
Well, that's kind of baffling. This week I built the plugin on an Azure VM running Ubuntu 17.10, on a Linode VM running Ubuntu 16.04, on my work machine running Debian 9 and a couple of hours ago on OS X 10.12, and all worked fine just executing `make`.

I'll see if I can reproduce it at work on monday, but I think moving the flag position shouldn't matter and it's odd that it behaves differently . My first guess was that there's a specific bug in Go 1.10.2 regarding cgo or something of the sort, but I just downloaded 1.10.2 to test it and it builds fine here. For what is worth, I started the plugin with 1.9.2, did the last changes on 1.10 and built it this week with the latest stable version, 1.10.3. Could you try with the newest version?

My second guess is that you have some weird or custom C compiler in place that doesn't play well with Go. I'm not sure which are in use on the different setups I mentioned, but they are probably the latest stable gcc version. I'm on a Mac right now and the gcc version throws this: `Apple LLVM version 9.0.0 (clang-900.0.39.2)`.

I'll let you know if I find or can think of anything leading to this issue.

**Comment by iegomez** [comment]
Did you have any luck? I haven't been able to reproduce it in any of my setups, so it sounds specific to yours. You could write some basic go file that exports functions using cgo and see if that compiles using the same schema from the Makefile. If it doesn't, then there's definitely something going on at your setup.

**Comment by vincems** [comment]
Hi - after upgrading to 1.10.3 and testing my latest compile - which definitely generated a SO rather than an executable - things started working :)  Not sure why - I'll experiment further once I have my project back on track - for now it's awesome to get a 'Not authorized' message :)

Thanks for your help.

**Comment by iegomez** [comment]
Great! 

I'll be closing this for now, but let me know if you run into any other issue.

Cheers!
