### ISSUE TITLE
Wrong signature in the README example for Custom backend

### ISSUE THREAD

**Issue by synweap15** [iegomez/mosquitto-go-auth#82]
The example in the Readme for Custom (experimental backend) shows the following signature for the `GetUser` method

https://github.com/iegomez/mosquitto-go-auth/blob/master/README.md#custom-experimental

(note there are 3 parameters), whereas the actual expected signature has only two parameters (clientid is omitted):

https://github.com/iegomez/mosquitto-go-auth/blob/52a9a8f8406924b9d31052c0e9c16f5307512f04/go-auth.go#L214

**Comment by iegomez** [comment]
Thanks for catching that, I'll fix it during this week.

**Comment by iegomez** [comment]
OK, checking it I believe it's useful to pass `clientid` to the custom plugin's user check too, so I'd say the README is correct and the implementation needs work. I'll open a PR for that in a few minutes.

**Comment by iegomez** [comment]
Merged https://github.com/iegomez/mosquitto-go-auth/pull/83.

**Comment by iegomez** [comment]
Closing for now, but reopen if you have any other concern.
