### ISSUE TITLE
MySQL backend: ACL query example not suited for mosquitto 1.5 and up

### ISSUE THREAD

**Issue by synweap15** [iegomez/mosquitto-go-auth#84]
**mosquitto**: 1.6.10
**mosquitto-go-auth**: 0.8.1 + modifications

I've followed the setup details for MySQL plugin as in README, and found ACL rejects for `subscribe` calls. After setting up additional logging, it seems that the `acc` value mosquitto is querying with is not from the `[1, 2, 3]` range - it's actually `MOSQ_ACL_SUBSCRIBE`, as defined in `mosquitto_plugin.h`:

```
#define MOSQ_ACL_NONE 0x00
#define MOSQ_ACL_READ 0x01
#define MOSQ_ACL_WRITE 0x02
#define MOSQ_ACL_SUBSCRIBE 0x04
```

MySQL query in README:

`SELECT topic FROM acl WHERE (username = ?) AND rw >= ?`

Therefore if you follow the README docs and examples and assume:
```
READ - 1
WRITE - 2
READWRITE - 3
```
you'd get git with `Acl check is false` upon subscription attempt since the query does not support `MOSQ_ACL_SUBSCRIBE`. 

More information: https://github.com/jpmens/mosquitto-auth-plug/issues/356
https://mosquitto.org/api/files2/mosquitto_plugin-h.html

**Comment by iegomez** [comment]
Yeah, the examples were written before `MOSQ_ACL_SUBSCRIBE` was introduced. I'll rewrite them along other docs on an ongoing PR.

**Comment by iegomez** [comment]
I'm adding some docs for this in a [PR](https://github.com/iegomez/mosquitto-go-auth/pull/81) I'll merge in a few minutes, but in any case there's some more info in older/closed issues like https://github.com/iegomez/mosquitto-go-auth/issues/46 and https://github.com/iegomez/mosquitto-go-auth/issues/18.

Hopefully the additions to the `README` will help in clarifying this. Thanks again for your report and contributions!

**Comment by iegomez** [comment]
Merged!
