### ISSUE TITLE
HTTP superuser URI not allowed to be empty

### ISSUE THREAD

**Issue by carlgreen** [iegomez/mosquitto-go-auth#85]
Contrary to the README which states that http_superuser_uri is not mandatory, the code in backends/http.go still requires this. It appears this was intended to be changed in e3ff0e847e5281668a34504cdfaaee9bbd16cb85, but has only been done for JWT. https://github.com/iegomez/mosquitto-go-auth/blob/63d59541dfc885a85b2e033bcdd46b36b99c80a9/backends/http.go#L73-L78

Like JWT the else should probably removed like:
```go
 if superuserUri, ok := authOpts["http_superuser_uri"]; ok { 
 	http.SuperuserUri = superuserUri 
 } 
```

**Comment by iegomez** [comment]
Ah, indeed, a check was added to return false when the uri is empty but the options weren't updated. I'll fix this in a minute.

**Comment by iegomez** [comment]
Just pushed the change to master. Thanks for reporting!
