### ISSUE TITLE
Error indtalling in raspberry

### ISSUE THREAD

**Issue by vicdaner** [iegomez/mosquitto-go-auth#86]
Hi!

I have a problem installig the plugin in a raspberry pi 4.

1st of all, a question, 
Can I use the mosquitto that is in the repositories or should I compile it?

I have try following the wiki 
- download mosquitto
-build mosquitto, add a mosquitto user and set ownership for /var/log/mosquitto and /var/lib/mosquitto/
-Create service
-Install go
- export PATH=$PATH:/usr/local/go/bin:~/go/bin
- source ~/.profile
- Install the plugin
export CGO_CFLAGS="-I/usr/local/include -fPIC"
export CGO_LDFLAGS="-shared"
make 

I get the next message 
`go build -buildmode=c-archive go-auth.go
go-auth.go:15:2: cannot find package "github.com/iegomez/mosquitto-go-auth/backends" in any of:
        /usr/local/go/src/github.com/iegomez/mosquitto-go-auth/backends (from $GOROOT)
        /home/pi/go/src/github.com/iegomez/mosquitto-go-auth/backends (from $GOPATH)
go-auth.go:16:2: cannot find package "github.com/iegomez/mosquitto-go-auth/cache" in any of:
        /usr/local/go/src/github.com/iegomez/mosquitto-go-auth/cache (from $GOROOT)
        /home/pi/go/src/github.com/iegomez/mosquitto-go-auth/cache (from $GOPATH)
go-auth.go:13:2: cannot find package "github.com/iegomez/mosquitto-go-auth/hashing" in any of:
        /usr/local/go/src/github.com/iegomez/mosquitto-go-auth/hashing (from $GOROOT)
        /home/pi/go/src/github.com/iegomez/mosquitto-go-auth/hashing (from $GOPATH)
go-auth.go:17:2: cannot find package "github.com/sirupsen/logrus" in any of:
        /usr/local/go/src/github.com/sirupsen/logrus (from $GOROOT)
        /home/pi/go/src/github.com/sirupsen/logrus (from $GOPATH)`

I don't really know where could be the problem :(

**Comment by iegomez** [comment]
That's odd. How did you install Go?

**Comment by iegomez** [comment]
Hey, @vicdaner. It's been some time since your reported this issue, and since there's been no follow up I'm gonna close it for the time being.
If you did find a fix for your issue, or have any more details, questions, etc., feel free to reopen the issue.

Cheers!
