### ISSUE TITLE
Question: MySQL ACL Check with MOSQ_ACL_SUBSCRIBE

### ISSUE THREAD

**Issue by S3phe** [iegomez/mosquitto-go-auth#87]
Hello,

I have questions regarding Mosquitto 1.5 permission "MOSQ_ACL_SUBSCRIBE (0x04)" and acl via MySQL.

My clients subscribe to "#" after connect, and I gave them Read and Write permission via acl for USERNAME/#. (Pattern readwrite %u/#)

(-> So I was able to decide on my broker's acl which topics they were joining.)

It seems that this way is impossible with mosquitto-go-auth.

In this example my client has the username: "peter".

In my mosquitto.conf:
`auth_opt_mysql_userquery SELECT password_hash FROM user WHERE username = ? AND is_active = true LIMIT 1`
`auth_opt_mysql_superquery SELECT count(*) FROM user WHERE username = ? AND is_admin = true AND is_active = true`
`auth_opt_mysql_aclquery SELECT topic FROM acl WHERE (username = ?) AND (rw = ?)`
`allow_anonymous false`

"acl"-table in MySQL looks like this:
`id | username | topic | rw`
`1 | peter | # | 4`
`2 | peter | peter/# | 1`
`3 | peter | peter/# | 2`

(Even combining id 3+4 with read (1) and write (2) to readwrite(3) to row: `4 | peter | peter/# | 3` did not work!)

Like in postgres the aclquery can not be modified to "AND (rw = ? or $2 = 4)", because auth_opt_mysql only accepts "?" and not $1 and $2.

So my questions:
- Is it possible with your acls to create a pattern like "every user can subscribe+read+write to all subtopic under its username"? (Like %u/#=3) 

- Is it possible to realize the "old" behaviour: -> "Every User which has read or write permission to a topic is always allowed to subscribe that topic" ?

- Maybe its possible to use an acl file for patterns AND MySQL Backend for additional permissions?

**Comment by S3phe** [comment]
Update:
I found an sub-optimal workaround.

In mosquitto.conf I enabled "files" as second backend, where I created an `acl.conf` with the following content:
`pattern readwrite %u/#`

So through the "files"-backend, everyone is allowed to readwrite under their username. 

But I still have to add MOSQ-ACL_SUBSCRIBE in my acl-table.

**Comment by iegomez** [comment]
Hey! I'm not sure this would work and can't test it right now, but could you try this as a quick alternative to Postgres' `AND (rw = $2 or $2 = 4)`?
```
auth_opt_mysql_aclquery SELECT topic FROM acl WHERE (username = ?) AND (rw IN (?, 4))
```
If that doesn't work, I'll give it a better look since it might involve doing some changes to the backend to allow for this type of queries.

As for your workaround, wouldn't just defining 1, 2 and 4 for each topic achieve the same so you don't need 2 backends? E.g.:
```
id | username | topic | rw
1 | peter | peter/# | 4
2 | peter | peter/# | 1
3 | peter | peter/# | 2
```

**Comment by HelloHungryImDad** [comment]
Hi, I am also facing this issue.

I would like to grant MOSQ-ACL_SUBSCRIBE access to topics of the form foo/# but it does not work for publishing, only subscribing.

Topic wildcard # works for all levels however.

I tried the above suggestion but it didn't work for me.

This would be really useful to have working as I'm trying to implement authentication for a Sparkplug B system and wildcard topic publishing ACLs would be really useful.

For reference, I have enabled websockets which other users have reported ACL bugs with in the past.

**Comment by iegomez** [comment]
Hey, @S3phe. Did you ever give the suggestion a try? Just wanna know if there's something I need to do or it's already been resolved. If it was, please share results if you can/want, and feel free to close the issue afterwards. I not, no worries, I'll wait a few days and close it later.

Cheers!

**Comment by ilyas-hallak** [comment]
I got the same issues and tried your solution and it worked! Thanks for that!
