### ISSUE TITLE
Default keylen not used for hash resulting in no hash

### ISSUE THREAD

**Issue by carlgreen** [iegomez/mosquitto-go-auth#88]
keylen is used to initialize shaSize, which is then set to sensible defaults if it is zero:

https://github.com/iegomez/mosquitto-go-auth/blob/aa487a9a05e3e4a0e4885d912c010d9d1baa99a9/pw-gen/pw.go#L25-L37

However further along keylen (which may be zero) is used in generating the hashes, when shaSize should be used:

https://github.com/iegomez/mosquitto-go-auth/blob/aa487a9a05e3e4a0e4885d912c010d9d1baa99a9/pw-gen/pw.go#L42-L47

like so:

```go
 case hashing.Argon2IDOpt: 
 	hashComparer = hashing.NewArgon2IDHasher(*saltSize, *iterations, shaSize, uint32(*memory), uint8(*parallelism)) 
 case hashing.BcryptOpt: 
 	hashComparer = hashing.NewBcryptHashComparer(*cost) 
 case hashing.Pbkdf2Opt: 
 	hashComparer = hashing.NewPBKDF2Hasher(*saltSize, *iterations, *algorithm, *saltEncoding, shaSize) 
```

**Comment by iegomez** [comment]
Ah, absolutely, a mistake when merging old hashing utilities with newly supported ones.
Thanks for reporting!

**Comment by iegomez** [comment]
Fixed! Thanks again.
