### ISSUE TITLE
Acl check with backend Mongo always returns false when trying to read a topic with acc 1 (read only)

### ISSUE THREAD

**Issue by atanasyordanov21** [iegomez/mosquitto-go-auth#93]
Hi,

Thank you for the great plugin!

I have an issue when using mongo backend, and when I want to give read only access (1). The plugin never allows reading and always returns "Acl is false for user..." (taken from the log). Everything else is correct - username, password, topic. If I only change the topic's acc in MongoDB from 1 to 3, then the user can read the topic, but with acc 1 this is impossible. The denial appears when the user wants to subscribe for the topic. I've tested with a couple of different topics and different usernames.

This is my setup:

mosquitto version is 1.6.11
mosquitto-go-auth is the latest 1.0.0 - downloaded and complied a week ago on 2020-08-13
Compiled with go version 1.13.14 linux/amd64
MongoDB server version is 4.2.8

**/etc/mosquitto/mosquitto.conf:**
...
auth_plugin /etc/mosquitto/go-auth.so
auth_opt_cache true
auth_opt_cache_reset true
auth_opt_auth_cache_seconds 30
auth_opt_acl_cache_seconds 30
auth_opt_log_level debug
auth_opt_log_dest file
auth_opt_log_file /var/log/mosquitto.log
auth_opt_disable_superuser true
auth_opt_hasher pbkdf2
auth_opt_backends mongo
auth_opt_mongo_username <myMongoUsername>
auth_opt_mongo_password <myMongoPassword>
...

**The record in MongoDB:**
{
    "_id" : ObjectId("5a4e760f708ba1a1601fa40f"),
    "username" : "myUsername",
    "password" : "myPasswordHash-PBKDF2",
    "superuser" : false,
    "acls" : [ 
        {
            "topic" : "my/test/topic",
            "acc" : 1
        }
    ]
}

**Extract from /var/log/mosquitto.log:**
2020-08-20T16:50:18: New client connected from <IP address> as MQTT-client-ID (p2, c1, k60, u'myUsername').
2020-08-20T16:50:18: No will message specified.
2020-08-20T16:50:18: Sending CONNACK to MQTT-client-ID (0, 0)
2020-08-20T16:50:18: Received SUBSCRIBE from MQTT-client-ID
2020-08-20T16:50:18:    my/test/topic (QoS 0)
time="2020-08-20T16:50:18+03:00" level=debug msg="checking acl cache for myUsername"
time="2020-08-20T16:50:18+03:00" level=debug msg="to auth record: [...]\n"
time="2020-08-20T16:50:18+03:00" level=debug msg="Acl check with backend Mongo"
time="2020-08-20T16:50:18+03:00" level=debug msg="setting acl cache (granted = false) for myUsername"
time="2020-08-20T16:50:18+03:00" level=debug msg="to auth record: [...]\n"
time="2020-08-20T16:50:18+03:00" level=debug msg="Acl is false for user myUsername"
2020-08-20T16:50:18: Sending SUBACK to MQTT-client-ID

My MQTT client is paho.javascript-1.0.3, which I use in several other projects with no issues.

If you need some other information, please let me know.

Thank you and best regards,
Atanas

**Comment by iegomez** [comment]
Hi @atanasyordanov21! Since you're receiving `subscribe` from the client, then consider adding a second `ACL` that grants `subscribe` to the user, that is `acc` value 4:
```
"acls" : [
  {
    "topic" : "my/test/topic",
    "acc" : 1
  },
  {
    "topic" : "my/test/topic",
    "acc" : 4
  }
]
```
Let me know if that works.

**Comment by atanasyordanov21** [comment]
Hi @iegomez 

Yes, that works perfectly. Thank you for your advice!

Actually, I read once again the part of the documentation where you've described the new MOSQ_ACL_SUBSCRIBE (since mosquitto 1.5), and it's clear enough: "_**Please take this into consideration when designing your ACL records on every backend.**_", but then I was only considering the following in the MongoDB part: "_**These rules consis of a "topic" string and an int "acc", where 1 means read only, 2 means write only and 3 means readwrite.**_".

Greetings,
Atanas

**Comment by iegomez** [comment]
> but then I was only considering the following in the MongoDB part: "_**These rules consis of a "topic" string and an int "acc", where 1 means read only, 2 means write only and 3 means readwrite.**_".

Ah, you're right, I should update that. Thanks for the catch!
