### ISSUE TITLE
Build plugin error

### ISSUE THREAD

**Issue by edemilson** [iegomez/mosquitto-go-auth#98]
Hi,

I try to compile plugin in ubuntu 20.04, but whent run make I receive that error: 

\# github.com/iegomez/mosquitto-go-auth/backends
backends/redis.go:104:14: cannot use clusterClient (type *redis.ClusterClient) as type RedisClient in assignment:
        *redis.ClusterClient does not implement RedisClient (wrong type for ReloadState method)
                have ReloadState(context.Context)
                want ReloadState(context.Context) error

Any know what this?
Thank you.

**Comment by iegomez** [comment]
@edemilson Looks like a wrong version of the redis client, but not sure why. Maybe running `go get -u github.com/go-redis/redis/v8` explicitly before making does the trick.

**Comment by RenzoBeux** [comment]
Hey, im sorry i have to open a closed issue, but when running that go command i get stuck at:

`go: finding github.com/dgryski/go-rendezvous latest`

usingo go 1.13.8 linux/amd64

**Comment by iegomez** [comment]
@RenzoBeux I'm reclosing it because that's a different package, it's not related to the original issue.
Please open a separate one if you can't figure out what's wrong. And do trying getting that package by itself first, iot might be something specific to it.

**Comment by RenzoBeux** [comment]
Hey, thanks for the fast response. That is the output to the command you mentioned early.

**Comment by iegomez** [comment]
Ok, but then it has nothing to do with the plugin (maybe it's the package, or your Go installation, etc.), I don't know how I can help.

**Comment by iegomez** [comment]
Sorry for the lack of help, I can't even try it now because I don't have my Linux machine with me right now.
I hope you can resolve it soon.

Cheers!

**Comment by iegomez** [comment]
For what it's worth, I recently updated the redis cluster package and they changed from returning an error to a void 'ReloadState' function, and I adjusted Redis backend to account for that. So in latest versions this should not be an issue. Since the problem that motivated the reopening of this issue is unrelated, I'm gonna close it as done.
